# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MPLPowderCut.ui'
#
# Created: Tue Nov 11 15:36:33 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MPLPowderCutMainWindow(object):
    def setupUi(self, MPLPowderCutMainWindow):
        MPLPowderCutMainWindow.setObjectName(_fromUtf8("MPLPowderCutMainWindow"))
        MPLPowderCutMainWindow.resize(1011, 811)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MPLPowderCutMainWindow.sizePolicy().hasHeightForWidth())
        MPLPowderCutMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MPLPowderCutMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MPLgroupBoxPlotConfig = QtGui.QGroupBox(self.centralwidget)
        self.MPLgroupBoxPlotConfig.setMinimumSize(QtCore.QSize(281, 460))
        self.MPLgroupBoxPlotConfig.setMaximumSize(QtCore.QSize(281, 460))
        self.MPLgroupBoxPlotConfig.setObjectName(_fromUtf8("MPLgroupBoxPlotConfig"))
        self.MPLcomboBoxMarker = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxMarker.setGeometry(QtCore.QRect(150, 110, 111, 19))
        self.MPLcomboBoxMarker.setMinimumSize(QtCore.QSize(0, 19))
        self.MPLcomboBoxMarker.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxMarker.setObjectName(_fromUtf8("MPLcomboBoxMarker"))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 101, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.MPLcomboBoxActiveWorkspace = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxActiveWorkspace.setGeometry(QtCore.QRect(10, 20, 251, 22))
        self.MPLcomboBoxActiveWorkspace.setObjectName(_fromUtf8("MPLcomboBoxActiveWorkspace"))
        self.MPLcomboBoxActiveWorkspace.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.MPLlineEditLabelsTitle = QtGui.QLineEdit(self.MPLgroupBoxPlotConfig)
        self.MPLlineEditLabelsTitle.setGeometry(QtCore.QRect(150, 200, 111, 20))
        self.MPLlineEditLabelsTitle.setObjectName(_fromUtf8("MPLlineEditLabelsTitle"))
        self.MPLlineEditLabelsLegend = QtGui.QLineEdit(self.MPLgroupBoxPlotConfig)
        self.MPLlineEditLabelsLegend.setGeometry(QtCore.QRect(150, 230, 111, 20))
        self.MPLlineEditLabelsLegend.setObjectName(_fromUtf8("MPLlineEditLabelsLegend"))
        self.label_10 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 111, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.MPLcomboBoxLineStyle = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxLineStyle.setGeometry(QtCore.QRect(150, 70, 111, 19))
        self.MPLcomboBoxLineStyle.setMinimumSize(QtCore.QSize(0, 19))
        self.MPLcomboBoxLineStyle.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxLineStyle.setObjectName(_fromUtf8("MPLcomboBoxLineStyle"))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxColor.setGeometry(QtCore.QRect(150, 50, 111, 19))
        self.MPLcomboBoxColor.setMinimumSize(QtCore.QSize(0, 19))
        self.MPLcomboBoxColor.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxColor.setObjectName(_fromUtf8("MPLcomboBoxColor"))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.MPLlineEditLabelsIntensity = QtGui.QLineEdit(self.MPLgroupBoxPlotConfig)
        self.MPLlineEditLabelsIntensity.setGeometry(QtCore.QRect(150, 170, 111, 20))
        self.MPLlineEditLabelsIntensity.setObjectName(_fromUtf8("MPLlineEditLabelsIntensity"))
        self.groupBox = QtGui.QGroupBox(self.MPLgroupBoxPlotConfig)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 261, 161))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.MPLlineEditTextAnnotate = QtGui.QLineEdit(self.groupBox)
        self.MPLlineEditTextAnnotate.setGeometry(QtCore.QRect(140, 30, 111, 20))
        self.MPLlineEditTextAnnotate.setObjectName(_fromUtf8("MPLlineEditTextAnnotate"))
        self.MPLpushButtonPlaceText = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonPlaceText.setGeometry(QtCore.QRect(140, 60, 51, 23))
        self.MPLpushButtonPlaceText.setObjectName(_fromUtf8("MPLpushButtonPlaceText"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 90, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.MPLcomboBoxArrow = QtGui.QComboBox(self.groupBox)
        self.MPLcomboBoxArrow.setGeometry(QtCore.QRect(140, 90, 111, 22))
        self.MPLcomboBoxArrow.setObjectName(_fromUtf8("MPLcomboBoxArrow"))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLpushButtonPlaceArrow = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonPlaceArrow.setGeometry(QtCore.QRect(140, 120, 51, 23))
        self.MPLpushButtonPlaceArrow.setObjectName(_fromUtf8("MPLpushButtonPlaceArrow"))
        self.MPLpushButtonRemoveText = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonRemoveText.setGeometry(QtCore.QRect(190, 60, 61, 23))
        self.MPLpushButtonRemoveText.setObjectName(_fromUtf8("MPLpushButtonRemoveText"))
        self.MPLpushButtonRemoveArrow = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonRemoveArrow.setGeometry(QtCore.QRect(190, 120, 61, 23))
        self.MPLpushButtonRemoveArrow.setObjectName(_fromUtf8("MPLpushButtonRemoveArrow"))
        self.MPLcomboBoxColorMarker = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxColorMarker.setGeometry(QtCore.QRect(150, 90, 111, 19))
        self.MPLcomboBoxColorMarker.setMinimumSize(QtCore.QSize(19, 0))
        self.MPLcomboBoxColorMarker.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxColorMarker.setObjectName(_fromUtf8("MPLcomboBoxColorMarker"))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.MPLcomboBoxLegendPos = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxLegendPos.setGeometry(QtCore.QRect(150, 260, 111, 22))
        self.MPLcomboBoxLegendPos.setObjectName(_fromUtf8("MPLcomboBoxLegendPos"))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxErrorColor.setGeometry(QtCore.QRect(150, 130, 111, 22))
        self.MPLcomboBoxErrorColor.setObjectName(_fromUtf8("MPLcomboBoxErrorColor"))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.MPLgroupBoxPlotConfig, 0, 1, 1, 1)
        self.groupBoxSettings = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxSettings.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBoxSettings.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBoxSettings.setObjectName(_fromUtf8("groupBoxSettings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxSettings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxErrorBars = QtGui.QCheckBox(self.groupBoxSettings)
        self.checkBoxErrorBars.setMinimumSize(QtCore.QSize(0, 23))
        self.checkBoxErrorBars.setObjectName(_fromUtf8("checkBoxErrorBars"))
        self.verticalLayout_2.addWidget(self.checkBoxErrorBars)
        self.checkBoxUseNorm = QtGui.QCheckBox(self.groupBoxSettings)
        self.checkBoxUseNorm.setMinimumSize(QtCore.QSize(0, 23))
        self.checkBoxUseNorm.setChecked(True)
        self.checkBoxUseNorm.setObjectName(_fromUtf8("checkBoxUseNorm"))
        self.verticalLayout_2.addWidget(self.checkBoxUseNorm)
        self.checkBoxRemoveNans = QtGui.QCheckBox(self.groupBoxSettings)
        self.checkBoxRemoveNans.setMinimumSize(QtCore.QSize(0, 23))
        self.checkBoxRemoveNans.setChecked(True)
        self.checkBoxRemoveNans.setObjectName(_fromUtf8("checkBoxRemoveNans"))
        self.verticalLayout_2.addWidget(self.checkBoxRemoveNans)
        self.gridLayout.addWidget(self.groupBoxSettings, 1, 1, 1, 1)
        self.MPLgroupBoxDataFormat = QtGui.QGroupBox(self.centralwidget)
        self.MPLgroupBoxDataFormat.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLgroupBoxDataFormat.sizePolicy().hasHeightForWidth())
        self.MPLgroupBoxDataFormat.setSizePolicy(sizePolicy)
        self.MPLgroupBoxDataFormat.setMinimumSize(QtCore.QSize(555, 131))
        self.MPLgroupBoxDataFormat.setMaximumSize(QtCore.QSize(491, 200))
        self.MPLgroupBoxDataFormat.setCheckable(False)
        self.MPLgroupBoxDataFormat.setChecked(False)
        self.MPLgroupBoxDataFormat.setObjectName(_fromUtf8("MPLgroupBoxDataFormat"))
        self.label_66 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_66.setGeometry(QtCore.QRect(90, 110, 21, 20))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.MPLcomboBoxPowderCutY = QtGui.QComboBox(self.MPLgroupBoxDataFormat)
        self.MPLcomboBoxPowderCutY.setGeometry(QtCore.QRect(110, 110, 69, 22))
        self.MPLcomboBoxPowderCutY.setObjectName(_fromUtf8("MPLcomboBoxPowderCutY"))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.label_61 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_61.setGeometry(QtCore.QRect(310, 80, 21, 16))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.MPLlineEditPowderCutAlongTo = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutAlongTo.setGeometry(QtCore.QRect(330, 50, 71, 20))
        self.MPLlineEditPowderCutAlongTo.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongTo"))
        self.MPLlineEditPowderCutYFrom = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutYFrom.setGeometry(QtCore.QRect(230, 110, 71, 20))
        self.MPLlineEditPowderCutYFrom.setObjectName(_fromUtf8("MPLlineEditPowderCutYFrom"))
        self.MPLlineEditPowderCutThickTo = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutThickTo.setGeometry(QtCore.QRect(330, 80, 71, 20))
        self.MPLlineEditPowderCutThickTo.setObjectName(_fromUtf8("MPLlineEditPowderCutThickTo"))
        self.MPLlineEditPowderCutThickFrom = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutThickFrom.setGeometry(QtCore.QRect(230, 80, 71, 20))
        self.MPLlineEditPowderCutThickFrom.setObjectName(_fromUtf8("MPLlineEditPowderCutThickFrom"))
        self.label_62 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_62.setGeometry(QtCore.QRect(430, 80, 41, 16))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.MPLlineEditPowderCutAlongFrom = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutAlongFrom.setGeometry(QtCore.QRect(230, 50, 71, 20))
        self.MPLlineEditPowderCutAlongFrom.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongFrom"))
        self.MPLlineEditPowderCutAlongStep = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutAlongStep.setGeometry(QtCore.QRect(490, 50, 51, 20))
        self.MPLlineEditPowderCutAlongStep.setText(_fromUtf8(""))
        self.MPLlineEditPowderCutAlongStep.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongStep"))
        self.label_57 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_57.setGeometry(QtCore.QRect(70, 50, 51, 20))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_67 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_67.setGeometry(QtCore.QRect(310, 110, 21, 16))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_63 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_63.setGeometry(QtCore.QRect(310, 50, 21, 16))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_59 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_59.setGeometry(QtCore.QRect(200, 50, 41, 16))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.MPLlineEditPowderCutYTo = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutYTo.setGeometry(QtCore.QRect(330, 110, 71, 20))
        self.MPLlineEditPowderCutYTo.setObjectName(_fromUtf8("MPLlineEditPowderCutYTo"))
        self.label_58 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_58.setGeometry(QtCore.QRect(190, 110, 51, 20))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.MPLcomboBoxPowderCutThick = QtGui.QComboBox(self.MPLgroupBoxDataFormat)
        self.MPLcomboBoxPowderCutThick.setGeometry(QtCore.QRect(110, 80, 69, 22))
        self.MPLcomboBoxPowderCutThick.setObjectName(_fromUtf8("MPLcomboBoxPowderCutThick"))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong = QtGui.QComboBox(self.MPLgroupBoxDataFormat)
        self.MPLcomboBoxPowderCutAlong.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.MPLcomboBoxPowderCutAlong.setObjectName(_fromUtf8("MPLcomboBoxPowderCutAlong"))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLlineEditPowderCutAlongNbins = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutAlongNbins.setGeometry(QtCore.QRect(490, 30, 51, 20))
        self.MPLlineEditPowderCutAlongNbins.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongNbins"))
        self.radioButtonNBins = QtGui.QRadioButton(self.MPLgroupBoxDataFormat)
        self.radioButtonNBins.setGeometry(QtCore.QRect(410, 30, 82, 17))
        self.radioButtonNBins.setChecked(True)
        self.radioButtonNBins.setObjectName(_fromUtf8("radioButtonNBins"))
        self.radioButtonBinWidth = QtGui.QRadioButton(self.MPLgroupBoxDataFormat)
        self.radioButtonBinWidth.setGeometry(QtCore.QRect(410, 50, 82, 17))
        self.radioButtonBinWidth.setObjectName(_fromUtf8("radioButtonBinWidth"))
        self.MPLspinBoxAlong = QtGui.QSpinBox(self.MPLgroupBoxDataFormat)
        self.MPLspinBoxAlong.setGeometry(QtCore.QRect(10, 50, 51, 22))
        self.MPLspinBoxAlong.setMaximum(99999)
        self.MPLspinBoxAlong.setProperty(_fromUtf8("value"), 100)
        self.MPLspinBoxAlong.setObjectName(_fromUtf8("MPLspinBoxAlong"))
        self.MPLspinBoxThick = QtGui.QSpinBox(self.MPLgroupBoxDataFormat)
        self.MPLspinBoxThick.setGeometry(QtCore.QRect(10, 80, 51, 22))
        self.MPLspinBoxThick.setMaximum(99999)
        self.MPLspinBoxThick.setProperty(_fromUtf8("value"), 100)
        self.MPLspinBoxThick.setObjectName(_fromUtf8("MPLspinBoxThick"))
        self.label = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_13 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_13.setGeometry(QtCore.QRect(410, 10, 131, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.MPLlineEditPowderCutWidth = QtGui.QLineEdit(self.MPLgroupBoxDataFormat)
        self.MPLlineEditPowderCutWidth.setGeometry(QtCore.QRect(492, 80, 51, 20))
        self.MPLlineEditPowderCutWidth.setObjectName(_fromUtf8("MPLlineEditPowderCutWidth"))
        self.label_60 = QtGui.QLabel(self.MPLgroupBoxDataFormat)
        self.label_60.setGeometry(QtCore.QRect(200, 80, 41, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.MPLgroupBoxDataFormat, 3, 0, 1, 1)
        self.MPLgroupBoxControls = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLgroupBoxControls.sizePolicy().hasHeightForWidth())
        self.MPLgroupBoxControls.setSizePolicy(sizePolicy)
        self.MPLgroupBoxControls.setMinimumSize(QtCore.QSize(281, 150))
        self.MPLgroupBoxControls.setMaximumSize(QtCore.QSize(231, 200))
        self.MPLgroupBoxControls.setObjectName(_fromUtf8("MPLgroupBoxControls"))
        self.MPLpushButtonDone = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonDone.setGeometry(QtCore.QRect(20, 140, 201, 23))
        self.MPLpushButtonDone.setObjectName(_fromUtf8("MPLpushButtonDone"))
        self.MPLpushButtonOPlot = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonOPlot.setGeometry(QtCore.QRect(130, 50, 91, 23))
        self.MPLpushButtonOPlot.setObjectName(_fromUtf8("MPLpushButtonOPlot"))
        self.MPLpushButtonPlot = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonPlot.setGeometry(QtCore.QRect(20, 50, 91, 23))
        self.MPLpushButtonPlot.setObjectName(_fromUtf8("MPLpushButtonPlot"))
        self.MPLpushButtonPopPlot = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonPopPlot.setGeometry(QtCore.QRect(20, 80, 91, 23))
        self.MPLpushButtonPopPlot.setObjectName(_fromUtf8("MPLpushButtonPopPlot"))
        self.MPLpushButtonSaveASCII = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonSaveASCII.setGeometry(QtCore.QRect(130, 80, 91, 23))
        self.MPLpushButtonSaveASCII.setObjectName(_fromUtf8("MPLpushButtonSaveASCII"))
        self.MPLpushButtonImportData = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonImportData.setGeometry(QtCore.QRect(20, 20, 201, 23))
        self.MPLpushButtonImportData.setObjectName(_fromUtf8("MPLpushButtonImportData"))
        self.MPLpushButtonSavePlotWS = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonSavePlotWS.setGeometry(QtCore.QRect(130, 110, 91, 23))
        self.MPLpushButtonSavePlotWS.setObjectName(_fromUtf8("MPLpushButtonSavePlotWS"))
        self.MPLpushButtonSaveHistory = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonSaveHistory.setGeometry(QtCore.QRect(20, 110, 91, 23))
        self.MPLpushButtonSaveHistory.setObjectName(_fromUtf8("MPLpushButtonSaveHistory"))
        self.gridLayout.addWidget(self.MPLgroupBoxControls, 2, 1, 2, 1)
        self.MPLtabWidgetPlotHistory = QtGui.QTabWidget(self.centralwidget)
        self.MPLtabWidgetPlotHistory.setMinimumSize(QtCore.QSize(550, 600))
        self.MPLtabWidgetPlotHistory.setObjectName(_fromUtf8("MPLtabWidgetPlotHistory"))
        self.tabPlot = QtGui.QWidget()
        self.tabPlot.setObjectName(_fromUtf8("tabPlot"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabPlot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.MPLframe = QtGui.QFrame(self.tabPlot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLframe.sizePolicy().hasHeightForWidth())
        self.MPLframe.setSizePolicy(sizePolicy)
        self.MPLframe.setMinimumSize(QtCore.QSize(544, 544))
        self.MPLframe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MPLframe.setAutoFillBackground(True)
        self.MPLframe.setFrameShape(QtGui.QFrame.Box)
        self.MPLframe.setFrameShadow(QtGui.QFrame.Raised)
        self.MPLframe.setLineWidth(2)
        self.MPLframe.setObjectName(_fromUtf8("MPLframe"))
        self.gridLayout_2.addWidget(self.MPLframe, 0, 0, 1, 1)
        self.MPLtabWidgetPlotHistory.addTab(self.tabPlot, _fromUtf8(""))
        self.tabHistory = QtGui.QWidget()
        self.tabHistory.setObjectName(_fromUtf8("tabHistory"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabHistory)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MPLpushButtonUpdateHistory = QtGui.QPushButton(self.tabHistory)
        self.MPLpushButtonUpdateHistory.setMaximumSize(QtCore.QSize(130, 23))
        self.MPLpushButtonUpdateHistory.setObjectName(_fromUtf8("MPLpushButtonUpdateHistory"))
        self.horizontalLayout.addWidget(self.MPLpushButtonUpdateHistory)
        self.MPLcheckBoxExpandAll = QtGui.QCheckBox(self.tabHistory)
        self.MPLcheckBoxExpandAll.setMinimumSize(QtCore.QSize(90, 0))
        self.MPLcheckBoxExpandAll.setMaximumSize(QtCore.QSize(90, 16777215))
        self.MPLcheckBoxExpandAll.setObjectName(_fromUtf8("MPLcheckBoxExpandAll"))
        self.horizontalLayout.addWidget(self.MPLcheckBoxExpandAll)
        self.MPLlabelWSName = QtGui.QLabel(self.tabHistory)
        self.MPLlabelWSName.setMinimumSize(QtCore.QSize(330, 20))
        self.MPLlabelWSName.setMaximumSize(QtCore.QSize(330, 30))
        self.MPLlabelWSName.setObjectName(_fromUtf8("MPLlabelWSName"))
        self.horizontalLayout.addWidget(self.MPLlabelWSName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeWidgetHistory = QtGui.QTreeWidget(self.tabHistory)
        self.treeWidgetHistory.setObjectName(_fromUtf8("treeWidgetHistory"))
        self.verticalLayout.addWidget(self.treeWidgetHistory)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.MPLtabWidgetPlotHistory.addTab(self.tabHistory, _fromUtf8(""))
        self.tabComments = QtGui.QWidget()
        self.tabComments.setObjectName(_fromUtf8("tabComments"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabComments)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.MPLtextEditComments = QtGui.QTextEdit(self.tabComments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLtextEditComments.sizePolicy().hasHeightForWidth())
        self.MPLtextEditComments.setSizePolicy(sizePolicy)
        self.MPLtextEditComments.setReadOnly(True)
        self.MPLtextEditComments.setObjectName(_fromUtf8("MPLtextEditComments"))
        self.gridLayout_3.addWidget(self.MPLtextEditComments, 4, 0, 1, 4)
        self.MPLpushButtonSaveComments = QtGui.QPushButton(self.tabComments)
        self.MPLpushButtonSaveComments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLpushButtonSaveComments.sizePolicy().hasHeightForWidth())
        self.MPLpushButtonSaveComments.setSizePolicy(sizePolicy)
        self.MPLpushButtonSaveComments.setMinimumSize(QtCore.QSize(130, 0))
        self.MPLpushButtonSaveComments.setMaximumSize(QtCore.QSize(130, 16777215))
        self.MPLpushButtonSaveComments.setSizeIncrement(QtCore.QSize(0, 0))
        self.MPLpushButtonSaveComments.setBaseSize(QtCore.QSize(0, 0))
        self.MPLpushButtonSaveComments.setObjectName(_fromUtf8("MPLpushButtonSaveComments"))
        self.gridLayout_3.addWidget(self.MPLpushButtonSaveComments, 1, 0, 1, 1)
        self.MPLlabelCSelectedWorkspace = QtGui.QLabel(self.tabComments)
        self.MPLlabelCSelectedWorkspace.setMinimumSize(QtCore.QSize(350, 0))
        self.MPLlabelCSelectedWorkspace.setMaximumSize(QtCore.QSize(350, 16777215))
        self.MPLlabelCSelectedWorkspace.setObjectName(_fromUtf8("MPLlabelCSelectedWorkspace"))
        self.gridLayout_3.addWidget(self.MPLlabelCSelectedWorkspace, 1, 3, 1, 1)
        self.MPLcheckBoxReadOnly = QtGui.QCheckBox(self.tabComments)
        self.MPLcheckBoxReadOnly.setMinimumSize(QtCore.QSize(130, 0))
        self.MPLcheckBoxReadOnly.setMaximumSize(QtCore.QSize(130, 16777215))
        self.MPLcheckBoxReadOnly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MPLcheckBoxReadOnly.setChecked(True)
        self.MPLcheckBoxReadOnly.setObjectName(_fromUtf8("MPLcheckBoxReadOnly"))
        self.gridLayout_3.addWidget(self.MPLcheckBoxReadOnly, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.MPLtabWidgetPlotHistory.addTab(self.tabComments, _fromUtf8(""))
        self.gridLayout.addWidget(self.MPLtabWidgetPlotHistory, 0, 0, 3, 1)
        MPLPowderCutMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MPLPowderCutMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MPLPowderCutMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MPLPowderCutMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MPLPowderCutMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MPLPowderCutMainWindow)
        self.MPLtabWidgetPlotHistory.setCurrentIndex(2)
        QtCore.QObject.connect(self.MPLpushButtonPlot, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.MPLpushButtonPlot.show)
        QtCore.QObject.connect(self.MPLcomboBoxActiveWorkspace, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.MPLcomboBoxActiveWorkspace.show)
        QtCore.QMetaObject.connectSlotsByName(MPLPowderCutMainWindow)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxPowderCutAlong, self.MPLlineEditPowderCutAlongFrom)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutAlongFrom, self.MPLlineEditPowderCutAlongTo)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutAlongTo, self.MPLlineEditPowderCutAlongStep)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutAlongStep, self.MPLcomboBoxPowderCutThick)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxPowderCutThick, self.MPLlineEditPowderCutThickFrom)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutThickFrom, self.MPLlineEditPowderCutThickTo)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutThickTo, self.MPLcomboBoxPowderCutY)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxPowderCutY, self.MPLlineEditPowderCutYFrom)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutYFrom, self.MPLlineEditPowderCutYTo)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditPowderCutYTo, self.MPLcomboBoxActiveWorkspace)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxActiveWorkspace, self.MPLcomboBoxColor)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxColor, self.MPLcomboBoxLineStyle)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxLineStyle, self.MPLcomboBoxColorMarker)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxColorMarker, self.MPLcomboBoxMarker)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxMarker, self.MPLlineEditLabelsIntensity)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditLabelsIntensity, self.MPLlineEditLabelsTitle)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditLabelsTitle, self.MPLlineEditLabelsLegend)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditLabelsLegend, self.MPLcomboBoxLegendPos)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxLegendPos, self.MPLlineEditTextAnnotate)
        MPLPowderCutMainWindow.setTabOrder(self.MPLlineEditTextAnnotate, self.MPLpushButtonPlaceText)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonPlaceText, self.MPLpushButtonRemoveText)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonRemoveText, self.MPLcomboBoxArrow)
        MPLPowderCutMainWindow.setTabOrder(self.MPLcomboBoxArrow, self.MPLpushButtonPlaceArrow)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonPlaceArrow, self.MPLpushButtonRemoveArrow)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonRemoveArrow, self.MPLpushButtonPlot)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonPlot, self.MPLpushButtonOPlot)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonOPlot, self.MPLpushButtonPopPlot)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonPopPlot, self.MPLpushButtonSaveASCII)
        MPLPowderCutMainWindow.setTabOrder(self.MPLpushButtonSaveASCII, self.MPLpushButtonDone)

    def retranslateUi(self, MPLPowderCutMainWindow):
        MPLPowderCutMainWindow.setWindowTitle(QtGui.QApplication.translate("MPLPowderCutMainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLgroupBoxPlotConfig.setTitle(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Plot Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Triangle Down", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Triangle Up", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Triangle Left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Triangle Right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(5, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(6, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Pentagon", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(7, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Star", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(8, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Hexagon1", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(9, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Hexagon2", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(10, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Plus", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(11, QtGui.QApplication.translate("MPLPowderCutMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(12, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(13, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Thin Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(14, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Vline", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(15, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Hline", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(16, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(17, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(18, QtGui.QApplication.translate("MPLPowderCutMainWindow", "None Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Title Label", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxActiveWorkspace.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Select Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Intensity Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Legend Label", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Solid", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "None Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(5, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(6, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(7, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Aquamarine", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(8, QtGui.QApplication.translate("MPLPowderCutMainWindow", "BlueViolet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(9, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Chocolate", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(10, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Coral", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(11, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(12, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkGreen", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(13, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkRed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(14, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(15, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(16, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Lime", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(17, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(18, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Wheat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Line Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Line Style", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Marker Style", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlineEditLabelsIntensity.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Intensity (arb. units)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Text:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPlaceText.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Place", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Arrow:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Point Left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Point Right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Point Up", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Point Down", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPlaceArrow.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Place", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonRemoveText.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonRemoveArrow.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(5, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(6, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(7, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Aquamarine", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(8, QtGui.QApplication.translate("MPLPowderCutMainWindow", "BlueViolet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(9, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Chocolate", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(10, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Coral", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(11, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(12, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkGreen", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(13, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkRed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(14, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(15, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(16, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Lime", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(17, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(18, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Wheat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Marker Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Legend Position", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "lower left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "lower right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(5, QtGui.QApplication.translate("MPLPowderCutMainWindow", "center left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(6, QtGui.QApplication.translate("MPLPowderCutMainWindow", "center right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(7, QtGui.QApplication.translate("MPLPowderCutMainWindow", "lower center", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(8, QtGui.QApplication.translate("MPLPowderCutMainWindow", "upper center", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(9, QtGui.QApplication.translate("MPLPowderCutMainWindow", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(5, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(6, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(7, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Aquamarine", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(8, QtGui.QApplication.translate("MPLPowderCutMainWindow", "BlueViolet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(9, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Chocolate", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(10, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Coral", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(11, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(12, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkGreen", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(13, QtGui.QApplication.translate("MPLPowderCutMainWindow", "DarkRed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(14, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(15, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(16, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Lime", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(17, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(18, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Wheat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Error Bar Color", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSettings.setTitle(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Use Plot to Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxErrorBars.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Show Error Bars - Use Plot to Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseNorm.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Normalize by Number of Events", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxRemoveNans.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Set NaN, inf, and -inf  to Zero Values", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLgroupBoxDataFormat.setTitle(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Data Formatting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Intensity", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "|Q|", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "2Theta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(4, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Det Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "thick:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "along", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "range:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "|Q|", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "2Theta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Det Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(1, QtGui.QApplication.translate("MPLPowderCutMainWindow", "|Q|", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(2, QtGui.QApplication.translate("MPLPowderCutMainWindow", "2Theta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(3, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Det Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlineEditPowderCutAlongNbins.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonNBins.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "# Bins", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBinWidth.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Bin Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Num 2D Bins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Num Bins - 1D Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlineEditPowderCutWidth.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "from:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLgroupBoxControls.setTitle(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonDone.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonOPlot.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "OPlot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPlot.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPopPlot.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Pop Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSaveASCII.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Save ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonImportData.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Import Data from Slice Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSavePlotWS.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Save Plot WS", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSaveHistory.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Save History", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLtabWidgetPlotHistory.setTabText(self.MPLtabWidgetPlotHistory.indexOf(self.tabPlot), QtGui.QApplication.translate("MPLPowderCutMainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonUpdateHistory.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Update History", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcheckBoxExpandAll.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Expand All", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlabelWSName.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Workspace:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetHistory.headerItem().setText(0, QtGui.QApplication.translate("MPLPowderCutMainWindow", "Main Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLtabWidgetPlotHistory.setTabText(self.MPLtabWidgetPlotHistory.indexOf(self.tabHistory), QtGui.QApplication.translate("MPLPowderCutMainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSaveComments.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Save Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlabelCSelectedWorkspace.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Workspace: ", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcheckBoxReadOnly.setText(QtGui.QApplication.translate("MPLPowderCutMainWindow", "Read Only", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLtabWidgetPlotHistory.setTabText(self.MPLtabWidgetPlotHistory.indexOf(self.tabComments), QtGui.QApplication.translate("MPLPowderCutMainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))

