# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MPL1DCut.ui'
#
# Created: Thu May 21 16:54:42 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MPL1DCutMainWindow(object):
    def setupUi(self, MPL1DCutMainWindow):
        MPL1DCutMainWindow.setObjectName(_fromUtf8("MPL1DCutMainWindow"))
        MPL1DCutMainWindow.resize(1055, 920)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MPL1DCutMainWindow.sizePolicy().hasHeightForWidth())
        MPL1DCutMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MPL1DCutMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MPLgroupBoxPlotConfig = QtGui.QGroupBox(self.centralwidget)
        self.MPLgroupBoxPlotConfig.setMinimumSize(QtCore.QSize(281, 460))
        self.MPLgroupBoxPlotConfig.setMaximumSize(QtCore.QSize(281, 460))
        self.MPLgroupBoxPlotConfig.setObjectName(_fromUtf8("MPLgroupBoxPlotConfig"))
        self.MPLcomboBoxMarker = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxMarker.setGeometry(QtCore.QRect(150, 110, 111, 19))
        self.MPLcomboBoxMarker.setMinimumSize(QtCore.QSize(0, 19))
        self.MPLcomboBoxMarker.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxMarker.setObjectName(_fromUtf8("MPLcomboBoxMarker"))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxMarker.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 101, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.MPLcomboBoxActiveWorkspace = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxActiveWorkspace.setGeometry(QtCore.QRect(10, 20, 251, 22))
        self.MPLcomboBoxActiveWorkspace.setObjectName(_fromUtf8("MPLcomboBoxActiveWorkspace"))
        self.MPLcomboBoxActiveWorkspace.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.MPLlineEditLabelsTitle = QtGui.QLineEdit(self.MPLgroupBoxPlotConfig)
        self.MPLlineEditLabelsTitle.setGeometry(QtCore.QRect(150, 200, 111, 20))
        self.MPLlineEditLabelsTitle.setObjectName(_fromUtf8("MPLlineEditLabelsTitle"))
        self.MPLlineEditLabelsLegend = QtGui.QLineEdit(self.MPLgroupBoxPlotConfig)
        self.MPLlineEditLabelsLegend.setGeometry(QtCore.QRect(150, 230, 111, 20))
        self.MPLlineEditLabelsLegend.setObjectName(_fromUtf8("MPLlineEditLabelsLegend"))
        self.label_10 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 111, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.MPLcomboBoxLineStyle = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxLineStyle.setGeometry(QtCore.QRect(150, 70, 111, 19))
        self.MPLcomboBoxLineStyle.setMinimumSize(QtCore.QSize(0, 19))
        self.MPLcomboBoxLineStyle.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxLineStyle.setObjectName(_fromUtf8("MPLcomboBoxLineStyle"))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxLineStyle.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxColor.setGeometry(QtCore.QRect(150, 50, 111, 19))
        self.MPLcomboBoxColor.setMinimumSize(QtCore.QSize(0, 19))
        self.MPLcomboBoxColor.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxColor.setObjectName(_fromUtf8("MPLcomboBoxColor"))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxColor.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.MPLlineEditLabelsIntensity = QtGui.QLineEdit(self.MPLgroupBoxPlotConfig)
        self.MPLlineEditLabelsIntensity.setGeometry(QtCore.QRect(150, 170, 111, 20))
        self.MPLlineEditLabelsIntensity.setObjectName(_fromUtf8("MPLlineEditLabelsIntensity"))
        self.groupBox = QtGui.QGroupBox(self.MPLgroupBoxPlotConfig)
        self.groupBox.setGeometry(QtCore.QRect(10, 320, 261, 131))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.MPLlineEditTextAnnotate = QtGui.QLineEdit(self.groupBox)
        self.MPLlineEditTextAnnotate.setGeometry(QtCore.QRect(140, 20, 111, 20))
        self.MPLlineEditTextAnnotate.setObjectName(_fromUtf8("MPLlineEditTextAnnotate"))
        self.MPLpushButtonPlaceText = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonPlaceText.setGeometry(QtCore.QRect(140, 40, 51, 23))
        self.MPLpushButtonPlaceText.setObjectName(_fromUtf8("MPLpushButtonPlaceText"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.MPLcomboBoxArrow = QtGui.QComboBox(self.groupBox)
        self.MPLcomboBoxArrow.setGeometry(QtCore.QRect(140, 70, 111, 22))
        self.MPLcomboBoxArrow.setObjectName(_fromUtf8("MPLcomboBoxArrow"))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLcomboBoxArrow.addItem(_fromUtf8(""))
        self.MPLpushButtonPlaceArrow = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonPlaceArrow.setGeometry(QtCore.QRect(140, 90, 51, 23))
        self.MPLpushButtonPlaceArrow.setObjectName(_fromUtf8("MPLpushButtonPlaceArrow"))
        self.MPLpushButtonRemoveText = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonRemoveText.setGeometry(QtCore.QRect(190, 40, 61, 23))
        self.MPLpushButtonRemoveText.setObjectName(_fromUtf8("MPLpushButtonRemoveText"))
        self.MPLpushButtonRemoveArrow = QtGui.QPushButton(self.groupBox)
        self.MPLpushButtonRemoveArrow.setGeometry(QtCore.QRect(190, 90, 61, 23))
        self.MPLpushButtonRemoveArrow.setObjectName(_fromUtf8("MPLpushButtonRemoveArrow"))
        self.MPLcomboBoxColorMarker = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxColorMarker.setGeometry(QtCore.QRect(150, 90, 111, 19))
        self.MPLcomboBoxColorMarker.setMinimumSize(QtCore.QSize(19, 0))
        self.MPLcomboBoxColorMarker.setMaximumSize(QtCore.QSize(16777215, 19))
        self.MPLcomboBoxColorMarker.setObjectName(_fromUtf8("MPLcomboBoxColorMarker"))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.MPLcomboBoxColorMarker.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.MPLcomboBoxLegendPos = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxLegendPos.setGeometry(QtCore.QRect(150, 260, 111, 22))
        self.MPLcomboBoxLegendPos.setObjectName(_fromUtf8("MPLcomboBoxLegendPos"))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxLegendPos.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor = QtGui.QComboBox(self.MPLgroupBoxPlotConfig)
        self.MPLcomboBoxErrorColor.setGeometry(QtCore.QRect(150, 130, 111, 22))
        self.MPLcomboBoxErrorColor.setObjectName(_fromUtf8("MPLcomboBoxErrorColor"))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.MPLcomboBoxErrorColor.addItem(_fromUtf8(""))
        self.label_12 = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.MPLlabelLegend = QtGui.QLabel(self.MPLgroupBoxPlotConfig)
        self.MPLlabelLegend.setGeometry(QtCore.QRect(10, 290, 131, 16))
        self.MPLlabelLegend.setObjectName(_fromUtf8("MPLlabelLegend"))
        self.MPLpushButtonLegendEdit = QtGui.QPushButton(self.MPLgroupBoxPlotConfig)
        self.MPLpushButtonLegendEdit.setGeometry(QtCore.QRect(150, 290, 111, 23))
        self.MPLpushButtonLegendEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MPLpushButtonLegendEdit.setFlat(False)
        self.MPLpushButtonLegendEdit.setObjectName(_fromUtf8("MPLpushButtonLegendEdit"))
        self.gridLayout.addWidget(self.MPLgroupBoxPlotConfig, 0, 1, 1, 1)
        self.groupBoxSettings = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxSettings.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBoxSettings.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBoxSettings.setObjectName(_fromUtf8("groupBoxSettings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxSettings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxErrorBars = QtGui.QCheckBox(self.groupBoxSettings)
        self.checkBoxErrorBars.setMinimumSize(QtCore.QSize(0, 23))
        self.checkBoxErrorBars.setChecked(True)
        self.checkBoxErrorBars.setObjectName(_fromUtf8("checkBoxErrorBars"))
        self.verticalLayout_2.addWidget(self.checkBoxErrorBars)
        self.checkBoxUseNorm = QtGui.QCheckBox(self.groupBoxSettings)
        self.checkBoxUseNorm.setMinimumSize(QtCore.QSize(0, 23))
        self.checkBoxUseNorm.setChecked(True)
        self.checkBoxUseNorm.setObjectName(_fromUtf8("checkBoxUseNorm"))
        self.verticalLayout_2.addWidget(self.checkBoxUseNorm)
        self.checkBoxRemoveNans = QtGui.QCheckBox(self.groupBoxSettings)
        self.checkBoxRemoveNans.setMinimumSize(QtCore.QSize(0, 23))
        self.checkBoxRemoveNans.setChecked(True)
        self.checkBoxRemoveNans.setObjectName(_fromUtf8("checkBoxRemoveNans"))
        self.verticalLayout_2.addWidget(self.checkBoxRemoveNans)
        self.gridLayout.addWidget(self.groupBoxSettings, 1, 1, 1, 1)
        self.MPLgroupBoxDataFormat = QtGui.QGroupBox(self.centralwidget)
        self.MPLgroupBoxDataFormat.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLgroupBoxDataFormat.sizePolicy().hasHeightForWidth())
        self.MPLgroupBoxDataFormat.setSizePolicy(sizePolicy)
        self.MPLgroupBoxDataFormat.setMinimumSize(QtCore.QSize(750, 131))
        self.MPLgroupBoxDataFormat.setMaximumSize(QtCore.QSize(750, 220))
        self.MPLgroupBoxDataFormat.setCheckable(False)
        self.MPLgroupBoxDataFormat.setChecked(False)
        self.MPLgroupBoxDataFormat.setObjectName(_fromUtf8("MPLgroupBoxDataFormat"))
        self.stackedWidgetCut = QtGui.QStackedWidget(self.MPLgroupBoxDataFormat)
        self.stackedWidgetCut.setGeometry(QtCore.QRect(20, 20, 721, 191))
        self.stackedWidgetCut.setObjectName(_fromUtf8("stackedWidgetCut"))
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.label_165 = QtGui.QLabel(self.page_9)
        self.label_165.setGeometry(QtCore.QRect(670, 20, 41, 20))
        self.label_165.setObjectName(_fromUtf8("label_165"))
        self.MPLpushButtonResetParams = QtGui.QPushButton(self.page_9)
        self.MPLpushButtonResetParams.setGeometry(QtCore.QRect(420, 100, 131, 23))
        self.MPLpushButtonResetParams.setObjectName(_fromUtf8("MPLpushButtonResetParams"))
        self.label_59 = QtGui.QLabel(self.page_9)
        self.label_59.setGeometry(QtCore.QRect(210, 40, 41, 16))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_67 = QtGui.QLabel(self.page_9)
        self.label_67.setGeometry(QtCore.QRect(320, 100, 21, 16))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_61 = QtGui.QLabel(self.page_9)
        self.label_61.setGeometry(QtCore.QRect(320, 70, 21, 16))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_58 = QtGui.QLabel(self.page_9)
        self.label_58.setGeometry(QtCore.QRect(200, 100, 51, 20))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.MPLlineEditPowderCutAlongTo = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutAlongTo.setGeometry(QtCore.QRect(340, 40, 71, 20))
        self.MPLlineEditPowderCutAlongTo.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongTo"))
        self.label_60 = QtGui.QLabel(self.page_9)
        self.label_60.setGeometry(QtCore.QRect(210, 70, 41, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.radioButtonNBins = QtGui.QRadioButton(self.page_9)
        self.radioButtonNBins.setGeometry(QtCore.QRect(420, 20, 82, 17))
        self.radioButtonNBins.setChecked(True)
        self.radioButtonNBins.setObjectName(_fromUtf8("radioButtonNBins"))
        self.label_63 = QtGui.QLabel(self.page_9)
        self.label_63.setGeometry(QtCore.QRect(320, 40, 21, 16))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.MPLlineEditPowderCutThickFrom = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutThickFrom.setGeometry(QtCore.QRect(240, 70, 71, 20))
        self.MPLlineEditPowderCutThickFrom.setObjectName(_fromUtf8("MPLlineEditPowderCutThickFrom"))
        self.MPLlineEditPowderCutAlongNbins = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutAlongNbins.setGeometry(QtCore.QRect(500, 20, 51, 20))
        self.MPLlineEditPowderCutAlongNbins.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongNbins"))
        self.MPLlineEditPowderCutAlongFrom = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutAlongFrom.setGeometry(QtCore.QRect(240, 40, 71, 20))
        self.MPLlineEditPowderCutAlongFrom.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongFrom"))
        self.MPLlineEditPowderCutYTo = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutYTo.setGeometry(QtCore.QRect(340, 100, 71, 20))
        self.MPLlineEditPowderCutYTo.setObjectName(_fromUtf8("MPLlineEditPowderCutYTo"))
        self.MPLlineEditPowderCutYFrom = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutYFrom.setGeometry(QtCore.QRect(240, 100, 71, 20))
        self.MPLlineEditPowderCutYFrom.setObjectName(_fromUtf8("MPLlineEditPowderCutYFrom"))
        self.MPLlineEditPowderCutAlongStep = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutAlongStep.setGeometry(QtCore.QRect(500, 40, 51, 20))
        self.MPLlineEditPowderCutAlongStep.setText(_fromUtf8(""))
        self.MPLlineEditPowderCutAlongStep.setObjectName(_fromUtf8("MPLlineEditPowderCutAlongStep"))
        self.label_57 = QtGui.QLabel(self.page_9)
        self.label_57.setGeometry(QtCore.QRect(50, 40, 51, 20))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.MPLcomboBoxPowderCutAlong = QtGui.QComboBox(self.page_9)
        self.MPLcomboBoxPowderCutAlong.setGeometry(QtCore.QRect(98, 40, 91, 22))
        self.MPLcomboBoxPowderCutAlong.setObjectName(_fromUtf8("MPLcomboBoxPowderCutAlong"))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutAlong.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick = QtGui.QComboBox(self.page_9)
        self.MPLcomboBoxPowderCutThick.setGeometry(QtCore.QRect(98, 70, 91, 22))
        self.MPLcomboBoxPowderCutThick.setObjectName(_fromUtf8("MPLcomboBoxPowderCutThick"))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutThick.addItem(_fromUtf8(""))
        self.label_66 = QtGui.QLabel(self.page_9)
        self.label_66.setGeometry(QtCore.QRect(70, 100, 21, 20))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.MPLlineEditPowderCutThickTo = QtGui.QLineEdit(self.page_9)
        self.MPLlineEditPowderCutThickTo.setGeometry(QtCore.QRect(340, 70, 71, 20))
        self.MPLlineEditPowderCutThickTo.setObjectName(_fromUtf8("MPLlineEditPowderCutThickTo"))
        self.radioButtonBinWidth = QtGui.QRadioButton(self.page_9)
        self.radioButtonBinWidth.setGeometry(QtCore.QRect(420, 40, 82, 17))
        self.radioButtonBinWidth.setObjectName(_fromUtf8("radioButtonBinWidth"))
        self.MPLcomboBoxPowderCutY = QtGui.QComboBox(self.page_9)
        self.MPLcomboBoxPowderCutY.setGeometry(QtCore.QRect(98, 100, 91, 22))
        self.MPLcomboBoxPowderCutY.setObjectName(_fromUtf8("MPLcomboBoxPowderCutY"))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.MPLcomboBoxPowderCutY.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.page_9)
        self.label_13.setGeometry(QtCore.QRect(420, 0, 131, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.stackedWidgetCut.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.lineEditSCCutIntensityTo = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutIntensityTo.setGeometry(QtCore.QRect(380, 150, 71, 20))
        self.lineEditSCCutIntensityTo.setObjectName(_fromUtf8("lineEditSCCutIntensityTo"))
        self.lineEditSCCutETo = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutETo.setGeometry(QtCore.QRect(380, 120, 71, 20))
        self.lineEditSCCutETo.setObjectName(_fromUtf8("lineEditSCCutETo"))
        self.label_176 = QtGui.QLabel(self.page_10)
        self.label_176.setGeometry(QtCore.QRect(230, 120, 41, 16))
        self.label_176.setObjectName(_fromUtf8("label_176"))
        self.label_177 = QtGui.QLabel(self.page_10)
        self.label_177.setGeometry(QtCore.QRect(360, 120, 21, 16))
        self.label_177.setObjectName(_fromUtf8("label_177"))
        self.label_178 = QtGui.QLabel(self.page_10)
        self.label_178.setGeometry(QtCore.QRect(230, 30, 41, 16))
        self.label_178.setObjectName(_fromUtf8("label_178"))
        self.label_179 = QtGui.QLabel(self.page_10)
        self.label_179.setGeometry(QtCore.QRect(230, 150, 41, 20))
        self.label_179.setObjectName(_fromUtf8("label_179"))
        self.label_180 = QtGui.QLabel(self.page_10)
        self.label_180.setGeometry(QtCore.QRect(360, 30, 21, 16))
        self.label_180.setObjectName(_fromUtf8("label_180"))
        self.lineEditSCCutYTo = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutYTo.setGeometry(QtCore.QRect(380, 60, 71, 20))
        self.lineEditSCCutYTo.setObjectName(_fromUtf8("lineEditSCCutYTo"))
        self.label_181 = QtGui.QLabel(self.page_10)
        self.label_181.setGeometry(QtCore.QRect(230, 60, 41, 16))
        self.label_181.setObjectName(_fromUtf8("label_181"))
        self.label_182 = QtGui.QLabel(self.page_10)
        self.label_182.setGeometry(QtCore.QRect(360, 60, 21, 16))
        self.label_182.setObjectName(_fromUtf8("label_182"))
        self.lineEditSCCutXTo = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutXTo.setGeometry(QtCore.QRect(380, 30, 71, 20))
        self.lineEditSCCutXTo.setObjectName(_fromUtf8("lineEditSCCutXTo"))
        self.label_184 = QtGui.QLabel(self.page_10)
        self.label_184.setGeometry(QtCore.QRect(360, 150, 21, 16))
        self.label_184.setObjectName(_fromUtf8("label_184"))
        self.lineEditSCCutXFrom = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutXFrom.setGeometry(QtCore.QRect(270, 30, 71, 20))
        self.lineEditSCCutXFrom.setObjectName(_fromUtf8("lineEditSCCutXFrom"))
        self.lineEditSCCutYFrom = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutYFrom.setGeometry(QtCore.QRect(270, 60, 71, 20))
        self.lineEditSCCutYFrom.setObjectName(_fromUtf8("lineEditSCCutYFrom"))
        self.comboBoxSCCutY = QtGui.QComboBox(self.page_10)
        self.comboBoxSCCutY.setGeometry(QtCore.QRect(90, 60, 131, 22))
        self.comboBoxSCCutY.setObjectName(_fromUtf8("comboBoxSCCutY"))
        self.comboBoxSCCutY.addItem(_fromUtf8(""))
        self.comboBoxSCCutY.addItem(_fromUtf8(""))
        self.comboBoxSCCutY.addItem(_fromUtf8(""))
        self.comboBoxSCCutY.addItem(_fromUtf8(""))
        self.comboBoxSCCutX = QtGui.QComboBox(self.page_10)
        self.comboBoxSCCutX.setGeometry(QtCore.QRect(90, 30, 131, 22))
        self.comboBoxSCCutX.setObjectName(_fromUtf8("comboBoxSCCutX"))
        self.comboBoxSCCutX.addItem(_fromUtf8(""))
        self.comboBoxSCCutX.addItem(_fromUtf8(""))
        self.comboBoxSCCutX.addItem(_fromUtf8(""))
        self.comboBoxSCCutX.addItem(_fromUtf8(""))
        self.comboBoxSCCutE = QtGui.QComboBox(self.page_10)
        self.comboBoxSCCutE.setGeometry(QtCore.QRect(90, 120, 131, 22))
        self.comboBoxSCCutE.setObjectName(_fromUtf8("comboBoxSCCutE"))
        self.comboBoxSCCutE.addItem(_fromUtf8(""))
        self.comboBoxSCCutE.addItem(_fromUtf8(""))
        self.comboBoxSCCutE.addItem(_fromUtf8(""))
        self.comboBoxSCCutE.addItem(_fromUtf8(""))
        self.lineEditSCCutIntensityFrom = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutIntensityFrom.setGeometry(QtCore.QRect(270, 150, 71, 20))
        self.lineEditSCCutIntensityFrom.setObjectName(_fromUtf8("lineEditSCCutIntensityFrom"))
        self.lineEditSCCutEFrom = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutEFrom.setGeometry(QtCore.QRect(270, 120, 71, 20))
        self.lineEditSCCutEFrom.setObjectName(_fromUtf8("lineEditSCCutEFrom"))
        self.label_185 = QtGui.QLabel(self.page_10)
        self.label_185.setGeometry(QtCore.QRect(40, 30, 31, 20))
        self.label_185.setObjectName(_fromUtf8("label_185"))
        self.label_186 = QtGui.QLabel(self.page_10)
        self.label_186.setGeometry(QtCore.QRect(60, 150, 16, 16))
        self.label_186.setObjectName(_fromUtf8("label_186"))
        self.comboBoxSCCutIntensity = QtGui.QComboBox(self.page_10)
        self.comboBoxSCCutIntensity.setGeometry(QtCore.QRect(90, 150, 131, 22))
        self.comboBoxSCCutIntensity.setObjectName(_fromUtf8("comboBoxSCCutIntensity"))
        self.comboBoxSCCutIntensity.addItem(_fromUtf8(""))
        self.comboBoxSCCutIntensity.addItem(_fromUtf8(""))
        self.comboBoxSCCutIntensity.addItem(_fromUtf8(""))
        self.comboBoxSCCutIntensity.addItem(_fromUtf8(""))
        self.comboBoxSCCutIntensity.addItem(_fromUtf8(""))
        self.lineEditSCCutZTo = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutZTo.setGeometry(QtCore.QRect(380, 90, 71, 20))
        self.lineEditSCCutZTo.setObjectName(_fromUtf8("lineEditSCCutZTo"))
        self.lineEditSCCutZFrom = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutZFrom.setGeometry(QtCore.QRect(270, 90, 71, 20))
        self.lineEditSCCutZFrom.setObjectName(_fromUtf8("lineEditSCCutZFrom"))
        self.label_187 = QtGui.QLabel(self.page_10)
        self.label_187.setGeometry(QtCore.QRect(360, 90, 21, 16))
        self.label_187.setObjectName(_fromUtf8("label_187"))
        self.comboBoxSCCutZ = QtGui.QComboBox(self.page_10)
        self.comboBoxSCCutZ.setGeometry(QtCore.QRect(90, 90, 131, 22))
        self.comboBoxSCCutZ.setObjectName(_fromUtf8("comboBoxSCCutZ"))
        self.comboBoxSCCutZ.addItem(_fromUtf8(""))
        self.comboBoxSCCutZ.addItem(_fromUtf8(""))
        self.comboBoxSCCutZ.addItem(_fromUtf8(""))
        self.comboBoxSCCutZ.addItem(_fromUtf8(""))
        self.label_188 = QtGui.QLabel(self.page_10)
        self.label_188.setGeometry(QtCore.QRect(230, 90, 41, 16))
        self.label_188.setObjectName(_fromUtf8("label_188"))
        self.lineEditSCCutXStep = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutXStep.setGeometry(QtCore.QRect(570, 20, 51, 20))
        self.lineEditSCCutXStep.setText(_fromUtf8(""))
        self.lineEditSCCutXStep.setObjectName(_fromUtf8("lineEditSCCutXStep"))
        self.radioButtonSCBinWidth = QtGui.QRadioButton(self.page_10)
        self.radioButtonSCBinWidth.setGeometry(QtCore.QRect(490, 20, 82, 17))
        self.radioButtonSCBinWidth.setObjectName(_fromUtf8("radioButtonSCBinWidth"))
        self.radioButtonSCNBins = QtGui.QRadioButton(self.page_10)
        self.radioButtonSCNBins.setGeometry(QtCore.QRect(490, 0, 82, 17))
        self.radioButtonSCNBins.setChecked(True)
        self.radioButtonSCNBins.setObjectName(_fromUtf8("radioButtonSCNBins"))
        self.pushButtonSCCShowParams = QtGui.QPushButton(self.page_10)
        self.pushButtonSCCShowParams.setGeometry(QtCore.QRect(490, 80, 131, 23))
        self.pushButtonSCCShowParams.setObjectName(_fromUtf8("pushButtonSCCShowParams"))
        self.lineEditSCCutXNbins = QtGui.QLineEdit(self.page_10)
        self.lineEditSCCutXNbins.setGeometry(QtCore.QRect(570, 0, 51, 20))
        self.lineEditSCCutXNbins.setObjectName(_fromUtf8("lineEditSCCutXNbins"))
        self.label_15 = QtGui.QLabel(self.page_10)
        self.label_15.setGeometry(QtCore.QRect(510, -20, 131, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.page_10)
        self.label_16.setGeometry(QtCore.QRect(690, 20, 31, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.stackedWidgetCut.addWidget(self.page_10)
        self.gridLayout.addWidget(self.MPLgroupBoxDataFormat, 3, 0, 1, 1)
        self.MPLgroupBoxControls = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLgroupBoxControls.sizePolicy().hasHeightForWidth())
        self.MPLgroupBoxControls.setSizePolicy(sizePolicy)
        self.MPLgroupBoxControls.setMinimumSize(QtCore.QSize(281, 150))
        self.MPLgroupBoxControls.setMaximumSize(QtCore.QSize(231, 200))
        self.MPLgroupBoxControls.setObjectName(_fromUtf8("MPLgroupBoxControls"))
        self.MPLpushButtonDone = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonDone.setGeometry(QtCore.QRect(20, 140, 201, 23))
        self.MPLpushButtonDone.setObjectName(_fromUtf8("MPLpushButtonDone"))
        self.MPLpushButtonOPlot = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonOPlot.setGeometry(QtCore.QRect(130, 50, 91, 23))
        self.MPLpushButtonOPlot.setObjectName(_fromUtf8("MPLpushButtonOPlot"))
        self.MPLpushButtonPlot = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonPlot.setGeometry(QtCore.QRect(20, 50, 91, 23))
        self.MPLpushButtonPlot.setObjectName(_fromUtf8("MPLpushButtonPlot"))
        self.MPLpushButtonPopPlot = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonPopPlot.setGeometry(QtCore.QRect(20, 80, 91, 23))
        self.MPLpushButtonPopPlot.setObjectName(_fromUtf8("MPLpushButtonPopPlot"))
        self.MPLpushButtonSaveASCII = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonSaveASCII.setGeometry(QtCore.QRect(130, 80, 91, 23))
        self.MPLpushButtonSaveASCII.setObjectName(_fromUtf8("MPLpushButtonSaveASCII"))
        self.MPLpushButtonImportData = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonImportData.setGeometry(QtCore.QRect(20, 20, 201, 23))
        self.MPLpushButtonImportData.setObjectName(_fromUtf8("MPLpushButtonImportData"))
        self.MPLpushButtonSavePlotWS = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonSavePlotWS.setGeometry(QtCore.QRect(130, 110, 91, 23))
        self.MPLpushButtonSavePlotWS.setObjectName(_fromUtf8("MPLpushButtonSavePlotWS"))
        self.MPLpushButtonSaveHistory = QtGui.QPushButton(self.MPLgroupBoxControls)
        self.MPLpushButtonSaveHistory.setGeometry(QtCore.QRect(20, 110, 91, 23))
        self.MPLpushButtonSaveHistory.setObjectName(_fromUtf8("MPLpushButtonSaveHistory"))
        self.gridLayout.addWidget(self.MPLgroupBoxControls, 2, 1, 2, 1)
        self.MPLtabWidgetPlotHistory = QtGui.QTabWidget(self.centralwidget)
        self.MPLtabWidgetPlotHistory.setMinimumSize(QtCore.QSize(550, 600))
        self.MPLtabWidgetPlotHistory.setObjectName(_fromUtf8("MPLtabWidgetPlotHistory"))
        self.tabPlot = QtGui.QWidget()
        self.tabPlot.setObjectName(_fromUtf8("tabPlot"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabPlot)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.MPLframe = QtGui.QFrame(self.tabPlot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLframe.sizePolicy().hasHeightForWidth())
        self.MPLframe.setSizePolicy(sizePolicy)
        self.MPLframe.setMinimumSize(QtCore.QSize(544, 544))
        self.MPLframe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MPLframe.setAutoFillBackground(True)
        self.MPLframe.setFrameShape(QtGui.QFrame.Box)
        self.MPLframe.setFrameShadow(QtGui.QFrame.Raised)
        self.MPLframe.setLineWidth(2)
        self.MPLframe.setObjectName(_fromUtf8("MPLframe"))
        self.gridLayout_2.addWidget(self.MPLframe, 0, 0, 1, 1)
        self.MPLtabWidgetPlotHistory.addTab(self.tabPlot, _fromUtf8(""))
        self.tabHistory = QtGui.QWidget()
        self.tabHistory.setObjectName(_fromUtf8("tabHistory"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabHistory)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MPLpushButtonUpdateHistory = QtGui.QPushButton(self.tabHistory)
        self.MPLpushButtonUpdateHistory.setMaximumSize(QtCore.QSize(130, 23))
        self.MPLpushButtonUpdateHistory.setObjectName(_fromUtf8("MPLpushButtonUpdateHistory"))
        self.horizontalLayout.addWidget(self.MPLpushButtonUpdateHistory)
        self.MPLcheckBoxExpandAll = QtGui.QCheckBox(self.tabHistory)
        self.MPLcheckBoxExpandAll.setMinimumSize(QtCore.QSize(90, 0))
        self.MPLcheckBoxExpandAll.setMaximumSize(QtCore.QSize(90, 16777215))
        self.MPLcheckBoxExpandAll.setObjectName(_fromUtf8("MPLcheckBoxExpandAll"))
        self.horizontalLayout.addWidget(self.MPLcheckBoxExpandAll)
        self.MPLlabelWSName = QtGui.QLabel(self.tabHistory)
        self.MPLlabelWSName.setMinimumSize(QtCore.QSize(330, 20))
        self.MPLlabelWSName.setMaximumSize(QtCore.QSize(330, 30))
        self.MPLlabelWSName.setObjectName(_fromUtf8("MPLlabelWSName"))
        self.horizontalLayout.addWidget(self.MPLlabelWSName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeWidgetHistory = QtGui.QTreeWidget(self.tabHistory)
        self.treeWidgetHistory.setObjectName(_fromUtf8("treeWidgetHistory"))
        self.verticalLayout.addWidget(self.treeWidgetHistory)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.MPLtabWidgetPlotHistory.addTab(self.tabHistory, _fromUtf8(""))
        self.tabComments = QtGui.QWidget()
        self.tabComments.setObjectName(_fromUtf8("tabComments"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabComments)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.MPLtextEditComments = QtGui.QTextEdit(self.tabComments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLtextEditComments.sizePolicy().hasHeightForWidth())
        self.MPLtextEditComments.setSizePolicy(sizePolicy)
        self.MPLtextEditComments.setReadOnly(True)
        self.MPLtextEditComments.setObjectName(_fromUtf8("MPLtextEditComments"))
        self.gridLayout_3.addWidget(self.MPLtextEditComments, 4, 0, 1, 4)
        self.MPLpushButtonSaveComments = QtGui.QPushButton(self.tabComments)
        self.MPLpushButtonSaveComments.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLpushButtonSaveComments.sizePolicy().hasHeightForWidth())
        self.MPLpushButtonSaveComments.setSizePolicy(sizePolicy)
        self.MPLpushButtonSaveComments.setMinimumSize(QtCore.QSize(130, 0))
        self.MPLpushButtonSaveComments.setMaximumSize(QtCore.QSize(130, 16777215))
        self.MPLpushButtonSaveComments.setSizeIncrement(QtCore.QSize(0, 0))
        self.MPLpushButtonSaveComments.setBaseSize(QtCore.QSize(0, 0))
        self.MPLpushButtonSaveComments.setObjectName(_fromUtf8("MPLpushButtonSaveComments"))
        self.gridLayout_3.addWidget(self.MPLpushButtonSaveComments, 1, 0, 1, 1)
        self.MPLlabelCSelectedWorkspace = QtGui.QLabel(self.tabComments)
        self.MPLlabelCSelectedWorkspace.setMinimumSize(QtCore.QSize(350, 0))
        self.MPLlabelCSelectedWorkspace.setMaximumSize(QtCore.QSize(350, 16777215))
        self.MPLlabelCSelectedWorkspace.setObjectName(_fromUtf8("MPLlabelCSelectedWorkspace"))
        self.gridLayout_3.addWidget(self.MPLlabelCSelectedWorkspace, 1, 3, 1, 1)
        self.MPLcheckBoxReadOnly = QtGui.QCheckBox(self.tabComments)
        self.MPLcheckBoxReadOnly.setMinimumSize(QtCore.QSize(130, 0))
        self.MPLcheckBoxReadOnly.setMaximumSize(QtCore.QSize(130, 16777215))
        self.MPLcheckBoxReadOnly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MPLcheckBoxReadOnly.setChecked(True)
        self.MPLcheckBoxReadOnly.setObjectName(_fromUtf8("MPLcheckBoxReadOnly"))
        self.gridLayout_3.addWidget(self.MPLcheckBoxReadOnly, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.MPLtabWidgetPlotHistory.addTab(self.tabComments, _fromUtf8(""))
        self.gridLayout.addWidget(self.MPLtabWidgetPlotHistory, 0, 0, 3, 1)
        MPL1DCutMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MPL1DCutMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MPL1DCutMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MPL1DCutMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MPL1DCutMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MPL1DCutMainWindow)
        self.MPLcomboBoxErrorColor.setCurrentIndex(2)
        self.stackedWidgetCut.setCurrentIndex(1)
        self.MPLtabWidgetPlotHistory.setCurrentIndex(0)
        QtCore.QObject.connect(self.MPLpushButtonPlot, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.MPLpushButtonPlot.show)
        QtCore.QObject.connect(self.MPLcomboBoxActiveWorkspace, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.MPLcomboBoxActiveWorkspace.show)
        QtCore.QMetaObject.connectSlotsByName(MPL1DCutMainWindow)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxActiveWorkspace, self.MPLcomboBoxColor)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxColor, self.MPLcomboBoxLineStyle)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxLineStyle, self.MPLcomboBoxColorMarker)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxColorMarker, self.MPLcomboBoxMarker)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxMarker, self.MPLlineEditLabelsIntensity)
        MPL1DCutMainWindow.setTabOrder(self.MPLlineEditLabelsIntensity, self.MPLlineEditLabelsTitle)
        MPL1DCutMainWindow.setTabOrder(self.MPLlineEditLabelsTitle, self.MPLlineEditLabelsLegend)
        MPL1DCutMainWindow.setTabOrder(self.MPLlineEditLabelsLegend, self.MPLcomboBoxLegendPos)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxLegendPos, self.MPLlineEditTextAnnotate)
        MPL1DCutMainWindow.setTabOrder(self.MPLlineEditTextAnnotate, self.MPLpushButtonPlaceText)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonPlaceText, self.MPLpushButtonRemoveText)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonRemoveText, self.MPLcomboBoxArrow)
        MPL1DCutMainWindow.setTabOrder(self.MPLcomboBoxArrow, self.MPLpushButtonPlaceArrow)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonPlaceArrow, self.MPLpushButtonRemoveArrow)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonRemoveArrow, self.MPLpushButtonPlot)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonPlot, self.MPLpushButtonOPlot)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonOPlot, self.MPLpushButtonPopPlot)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonPopPlot, self.MPLpushButtonSaveASCII)
        MPL1DCutMainWindow.setTabOrder(self.MPLpushButtonSaveASCII, self.MPLpushButtonDone)

    def retranslateUi(self, MPL1DCutMainWindow):
        MPL1DCutMainWindow.setWindowTitle(QtGui.QApplication.translate("MPL1DCutMainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLgroupBoxPlotConfig.setTitle(QtGui.QApplication.translate("MPL1DCutMainWindow", "Plot Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Triangle Down", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "Triangle Up", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Triangle Left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "Triangle Right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(5, QtGui.QApplication.translate("MPL1DCutMainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(6, QtGui.QApplication.translate("MPL1DCutMainWindow", "Pentagon", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(7, QtGui.QApplication.translate("MPL1DCutMainWindow", "Star", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(8, QtGui.QApplication.translate("MPL1DCutMainWindow", "Hexagon1", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(9, QtGui.QApplication.translate("MPL1DCutMainWindow", "Hexagon2", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(10, QtGui.QApplication.translate("MPL1DCutMainWindow", "Plus", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(11, QtGui.QApplication.translate("MPL1DCutMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(12, QtGui.QApplication.translate("MPL1DCutMainWindow", "Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(13, QtGui.QApplication.translate("MPL1DCutMainWindow", "Thin Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(14, QtGui.QApplication.translate("MPL1DCutMainWindow", "Vline", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(15, QtGui.QApplication.translate("MPL1DCutMainWindow", "Hline", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(16, QtGui.QApplication.translate("MPL1DCutMainWindow", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(17, QtGui.QApplication.translate("MPL1DCutMainWindow", "Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxMarker.setItemText(18, QtGui.QApplication.translate("MPL1DCutMainWindow", "None Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Title Label", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxActiveWorkspace.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Select Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Intensity Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Legend Label", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Solid", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "Dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLineStyle.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "None Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(5, QtGui.QApplication.translate("MPL1DCutMainWindow", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(6, QtGui.QApplication.translate("MPL1DCutMainWindow", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(7, QtGui.QApplication.translate("MPL1DCutMainWindow", "Aquamarine", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(8, QtGui.QApplication.translate("MPL1DCutMainWindow", "BlueViolet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(9, QtGui.QApplication.translate("MPL1DCutMainWindow", "Chocolate", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(10, QtGui.QApplication.translate("MPL1DCutMainWindow", "Coral", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(11, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(12, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkGreen", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(13, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkRed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(14, QtGui.QApplication.translate("MPL1DCutMainWindow", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(15, QtGui.QApplication.translate("MPL1DCutMainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(16, QtGui.QApplication.translate("MPL1DCutMainWindow", "Lime", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(17, QtGui.QApplication.translate("MPL1DCutMainWindow", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColor.setItemText(18, QtGui.QApplication.translate("MPL1DCutMainWindow", "Wheat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Line Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Line Style", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Marker Style", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlineEditLabelsIntensity.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Intensity (arb. units)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MPL1DCutMainWindow", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Text:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPlaceText.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Place", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Arrow:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Point Left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Point Right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "Point Up", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxArrow.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Point Down", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPlaceArrow.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Place", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonRemoveText.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonRemoveArrow.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(5, QtGui.QApplication.translate("MPL1DCutMainWindow", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(6, QtGui.QApplication.translate("MPL1DCutMainWindow", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(7, QtGui.QApplication.translate("MPL1DCutMainWindow", "Aquamarine", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(8, QtGui.QApplication.translate("MPL1DCutMainWindow", "BlueViolet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(9, QtGui.QApplication.translate("MPL1DCutMainWindow", "Chocolate", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(10, QtGui.QApplication.translate("MPL1DCutMainWindow", "Coral", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(11, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(12, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkGreen", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(13, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkRed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(14, QtGui.QApplication.translate("MPL1DCutMainWindow", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(15, QtGui.QApplication.translate("MPL1DCutMainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(16, QtGui.QApplication.translate("MPL1DCutMainWindow", "Lime", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(17, QtGui.QApplication.translate("MPL1DCutMainWindow", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxColorMarker.setItemText(18, QtGui.QApplication.translate("MPL1DCutMainWindow", "Wheat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Marker Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Legend Position", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "lower left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "lower right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(5, QtGui.QApplication.translate("MPL1DCutMainWindow", "center left", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(6, QtGui.QApplication.translate("MPL1DCutMainWindow", "center right", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(7, QtGui.QApplication.translate("MPL1DCutMainWindow", "lower center", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(8, QtGui.QApplication.translate("MPL1DCutMainWindow", "upper center", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxLegendPos.setItemText(9, QtGui.QApplication.translate("MPL1DCutMainWindow", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(5, QtGui.QApplication.translate("MPL1DCutMainWindow", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(6, QtGui.QApplication.translate("MPL1DCutMainWindow", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(7, QtGui.QApplication.translate("MPL1DCutMainWindow", "Aquamarine", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(8, QtGui.QApplication.translate("MPL1DCutMainWindow", "BlueViolet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(9, QtGui.QApplication.translate("MPL1DCutMainWindow", "Chocolate", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(10, QtGui.QApplication.translate("MPL1DCutMainWindow", "Coral", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(11, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(12, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkGreen", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(13, QtGui.QApplication.translate("MPL1DCutMainWindow", "DarkRed", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(14, QtGui.QApplication.translate("MPL1DCutMainWindow", "Gold", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(15, QtGui.QApplication.translate("MPL1DCutMainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(16, QtGui.QApplication.translate("MPL1DCutMainWindow", "Lime", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(17, QtGui.QApplication.translate("MPL1DCutMainWindow", "Violet", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxErrorColor.setItemText(18, QtGui.QApplication.translate("MPL1DCutMainWindow", "Wheat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Error Bar Color", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlabelLegend.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Edit Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonLegendEdit.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Edit Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSettings.setTitle(QtGui.QApplication.translate("MPL1DCutMainWindow", "Use Plot to Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxErrorBars.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Show Error Bars as + Sigma and - Sigma", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseNorm.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Normalize by Number of Events", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxRemoveNans.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Set NaN, inf, and -inf  to Zero Values", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLgroupBoxDataFormat.setTitle(QtGui.QApplication.translate("MPL1DCutMainWindow", "Data Formatting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_165.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Powder", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonResetParams.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Reset Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "thick:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonNBins.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "# Bins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlineEditPowderCutAlongNbins.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "along", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "|Q|", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "2Theta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutAlong.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Det Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "|Q|", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "2Theta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutThick.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "Det Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBinWidth.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Bin Width", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Intensity", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "|Q|", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "2Theta", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcomboBoxPowderCutY.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "Det Pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Num Bins - 1D Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_176.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "thick:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_177.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_178.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "from:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_179.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_180.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_181.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "thick:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_182.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_184.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutY.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "[H,0,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutY.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,K,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutY.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,0,L] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutY.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "E (meV)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutX.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "[H,0,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutX.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,K,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutX.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,0,L] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutX.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "E (meV)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutE.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "[H,0,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutE.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,K,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutE.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,0,L] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutE.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "E (meV)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_185.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "along", None, QtGui.QApplication.UnicodeUTF8))
        self.label_186.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutIntensity.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Intensity", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutIntensity.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "[H,0,0]", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutIntensity.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,K,0]", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutIntensity.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,0,L]", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutIntensity.setItemText(4, QtGui.QApplication.translate("MPL1DCutMainWindow", "E (meV)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_187.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "to:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutZ.setItemText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "[H,0,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutZ.setItemText(1, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,K,0] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutZ.setItemText(2, QtGui.QApplication.translate("MPL1DCutMainWindow", "[0,0,L] (RLU)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSCCutZ.setItemText(3, QtGui.QApplication.translate("MPL1DCutMainWindow", "E (meV)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_188.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "thick:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSCBinWidth.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Bin Width", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSCNBins.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "# Bins", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSCCShowParams.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Show Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSCCutXNbins.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Num Bins - 1D Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "SC", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLgroupBoxControls.setTitle(QtGui.QApplication.translate("MPL1DCutMainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonDone.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonOPlot.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "OPlot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPlot.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonPopPlot.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Pop Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSaveASCII.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Save ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonImportData.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Import Data from Slice Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSavePlotWS.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Save Plot WS", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSaveHistory.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Save History", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLtabWidgetPlotHistory.setTabText(self.MPLtabWidgetPlotHistory.indexOf(self.tabPlot), QtGui.QApplication.translate("MPL1DCutMainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonUpdateHistory.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Update History", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcheckBoxExpandAll.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Expand All", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlabelWSName.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Workspace:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetHistory.headerItem().setText(0, QtGui.QApplication.translate("MPL1DCutMainWindow", "Main Entry", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLtabWidgetPlotHistory.setTabText(self.MPLtabWidgetPlotHistory.indexOf(self.tabHistory), QtGui.QApplication.translate("MPL1DCutMainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLpushButtonSaveComments.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Save Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLlabelCSelectedWorkspace.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Workspace: ", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLcheckBoxReadOnly.setText(QtGui.QApplication.translate("MPL1DCutMainWindow", "Read Only", None, QtGui.QApplication.UnicodeUTF8))
        self.MPLtabWidgetPlotHistory.setTabText(self.MPLtabWidgetPlotHistory.indexOf(self.tabComments), QtGui.QApplication.translate("MPL1DCutMainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))

