# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_View1D.ui'
#
# Created: Thu May 21 13:54:42 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_View1DMainWindow(object):
    def setupUi(self, View1DMainWindow):
        View1DMainWindow.setObjectName(_fromUtf8("View1DMainWindow"))
        View1DMainWindow.resize(1055, 920)
        self.centralwidget = QtGui.QWidget(View1DMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frameView1D = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameView1D.sizePolicy().hasHeightForWidth())
        self.frameView1D.setSizePolicy(sizePolicy)
        self.frameView1D.setMinimumSize(QtCore.QSize(551, 353))
        self.frameView1D.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameView1D.setFrameShadow(QtGui.QFrame.Raised)
        self.frameView1D.setObjectName(_fromUtf8("frameView1D"))
        self.verticalLayout_2.addWidget(self.frameView1D)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(551, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(551, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 151, 73))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButtonSignal = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonSignal.setChecked(True)
        self.radioButtonSignal.setObjectName(_fromUtf8("radioButtonSignal"))
        self.verticalLayout.addWidget(self.radioButtonSignal)
        self.radioButtonEBar = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonEBar.setObjectName(_fromUtf8("radioButtonEBar"))
        self.verticalLayout.addWidget(self.radioButtonEBar)
        self.comboBoxPlotColor = QtGui.QComboBox(self.groupBox)
        self.comboBoxPlotColor.setGeometry(QtCore.QRect(30, 170, 121, 21))
        self.comboBoxPlotColor.setObjectName(_fromUtf8("comboBoxPlotColor"))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.comboBoxPlotColor.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 150, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBoxShowEBar = QtGui.QCheckBox(self.groupBox)
        self.checkBoxShowEBar.setGeometry(QtCore.QRect(30, 100, 161, 17))
        self.checkBoxShowEBar.setChecked(True)
        self.checkBoxShowEBar.setObjectName(_fromUtf8("checkBoxShowEBar"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.fontComboBox = QtGui.QFontComboBox(self.groupBox)
        self.fontComboBox.setGeometry(QtCore.QRect(230, 40, 161, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.fontComboBox.setFont(font)
        self.fontComboBox.setEditable(False)
        self.fontComboBox.setFontFilters(QtGui.QFontComboBox.MonospacedFonts|QtGui.QFontComboBox.ProportionalFonts|QtGui.QFontComboBox.ScalableFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(230, 70, 101, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBoxFontSize = QtGui.QComboBox(self.groupBox)
        self.comboBoxFontSize.setGeometry(QtCore.QRect(230, 90, 69, 22))
        self.comboBoxFontSize.setObjectName(_fromUtf8("comboBoxFontSize"))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.comboBoxFontSize.addItem(_fromUtf8(""))
        self.pushButtonUpdatePlot = QtGui.QPushButton(self.groupBox)
        self.pushButtonUpdatePlot.setGeometry(QtCore.QRect(430, 100, 91, 23))
        self.pushButtonUpdatePlot.setObjectName(_fromUtf8("pushButtonUpdatePlot"))
        self.checkBoxBoldFont = QtGui.QCheckBox(self.groupBox)
        self.checkBoxBoldFont.setGeometry(QtCore.QRect(230, 120, 91, 17))
        self.checkBoxBoldFont.setObjectName(_fromUtf8("checkBoxBoldFont"))
        self.pushButtonExit = QtGui.QPushButton(self.groupBox)
        self.pushButtonExit.setGeometry(QtCore.QRect(430, 170, 91, 23))
        self.pushButtonExit.setObjectName(_fromUtf8("pushButtonExit"))
        self.checkBoxShowPlotMarker = QtGui.QCheckBox(self.groupBox)
        self.checkBoxShowPlotMarker.setGeometry(QtCore.QRect(30, 120, 161, 17))
        self.checkBoxShowPlotMarker.setChecked(False)
        self.checkBoxShowPlotMarker.setObjectName(_fromUtf8("checkBoxShowPlotMarker"))
        self.comboBoxLineThick = QtGui.QComboBox(self.groupBox)
        self.comboBoxLineThick.setGeometry(QtCore.QRect(230, 170, 161, 22))
        self.comboBoxLineThick.setObjectName(_fromUtf8("comboBoxLineThick"))
        self.comboBoxLineThick.addItem(_fromUtf8(""))
        self.comboBoxLineThick.addItem(_fromUtf8(""))
        self.comboBoxLineThick.addItem(_fromUtf8(""))
        self.comboBoxEBarThick = QtGui.QComboBox(self.groupBox)
        self.comboBoxEBarThick.setGeometry(QtCore.QRect(230, 140, 161, 22))
        self.comboBoxEBarThick.setObjectName(_fromUtf8("comboBoxEBarThick"))
        self.comboBoxEBarThick.addItem(_fromUtf8(""))
        self.comboBoxEBarThick.addItem(_fromUtf8(""))
        self.comboBoxEBarThick.addItem(_fromUtf8(""))
        self.pushButtonSaveASCII = QtGui.QPushButton(self.groupBox)
        self.pushButtonSaveASCII.setGeometry(QtCore.QRect(430, 140, 91, 23))
        self.pushButtonSaveASCII.setObjectName(_fromUtf8("pushButtonSaveASCII"))
        self.verticalLayout_2.addWidget(self.groupBox)
        View1DMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(View1DMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        View1DMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(View1DMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        View1DMainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(View1DMainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(View1DMainWindow)
        self.comboBoxPlotColor.setCurrentIndex(0)
        self.fontComboBox.setCurrentIndex(58)
        self.comboBoxFontSize.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(View1DMainWindow)

    def retranslateUi(self, View1DMainWindow):
        View1DMainWindow.setWindowTitle(QtGui.QApplication.translate("View1DMainWindow", "View 1D Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("View1DMainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("View1DMainWindow", "Data Select", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSignal.setText(QtGui.QApplication.translate("View1DMainWindow", "Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonEBar.setText(QtGui.QApplication.translate("View1DMainWindow", "Error Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(0, QtGui.QApplication.translate("View1DMainWindow", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(1, QtGui.QApplication.translate("View1DMainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(2, QtGui.QApplication.translate("View1DMainWindow", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(3, QtGui.QApplication.translate("View1DMainWindow", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(4, QtGui.QApplication.translate("View1DMainWindow", "cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(5, QtGui.QApplication.translate("View1DMainWindow", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPlotColor.setItemText(6, QtGui.QApplication.translate("View1DMainWindow", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("View1DMainWindow", "Plot Color", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowEBar.setText(QtGui.QApplication.translate("View1DMainWindow", "Show Error Bars", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("View1DMainWindow", "Font Family", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("View1DMainWindow", "Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(0, QtGui.QApplication.translate("View1DMainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(1, QtGui.QApplication.translate("View1DMainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(2, QtGui.QApplication.translate("View1DMainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(3, QtGui.QApplication.translate("View1DMainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(4, QtGui.QApplication.translate("View1DMainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(5, QtGui.QApplication.translate("View1DMainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(6, QtGui.QApplication.translate("View1DMainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFontSize.setItemText(7, QtGui.QApplication.translate("View1DMainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUpdatePlot.setText(QtGui.QApplication.translate("View1DMainWindow", "Update Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBoldFont.setText(QtGui.QApplication.translate("View1DMainWindow", "Bold Font", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonExit.setText(QtGui.QApplication.translate("View1DMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowPlotMarker.setText(QtGui.QApplication.translate("View1DMainWindow", "Show Plot Symbols", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLineThick.setItemText(0, QtGui.QApplication.translate("View1DMainWindow", "Line: Thin", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLineThick.setItemText(1, QtGui.QApplication.translate("View1DMainWindow", "Line: Med", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLineThick.setItemText(2, QtGui.QApplication.translate("View1DMainWindow", "Line: Thick", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEBarThick.setItemText(0, QtGui.QApplication.translate("View1DMainWindow", "Error Bar: Thin", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEBarThick.setItemText(1, QtGui.QApplication.translate("View1DMainWindow", "Error Bar: Med", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEBarThick.setItemText(2, QtGui.QApplication.translate("View1DMainWindow", "Error Bar: Thick", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSaveASCII.setText(QtGui.QApplication.translate("View1DMainWindow", "Save ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("View1DMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("View1DMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

