# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_WorkspaceComposer.ui'
#
# Created: Fri Apr 24 18:18:10 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WorkspaceComposer(object):
    def setupUi(self, WorkspaceComposer):
        WorkspaceComposer.setObjectName(_fromUtf8("WorkspaceComposer"))
        WorkspaceComposer.resize(931, 528)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WorkspaceComposer.sizePolicy().hasHeightForWidth())
        WorkspaceComposer.setSizePolicy(sizePolicy)
        WorkspaceComposer.setMinimumSize(QtCore.QSize(900, 528))
        self.centralwidget = QtGui.QWidget(WorkspaceComposer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(931, 487))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(661, 341))
        self.groupBox_4.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidgetWGE = QtGui.QTableWidget(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetWGE.sizePolicy().hasHeightForWidth())
        self.tableWidgetWGE.setSizePolicy(sizePolicy)
        self.tableWidgetWGE.setMinimumSize(QtCore.QSize(671, 300))
        self.tableWidgetWGE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidgetWGE.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidgetWGE.setLineWidth(3)
        self.tableWidgetWGE.setRowCount(15)
        self.tableWidgetWGE.setColumnCount(7)
        self.tableWidgetWGE.setObjectName(_fromUtf8("tableWidgetWGE"))
        self.tableWidgetWGE.setColumnCount(7)
        self.tableWidgetWGE.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(6, item)
        self.tableWidgetWGE.horizontalHeader().setVisible(True)
        self.tableWidgetWGE.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetWGE.horizontalHeader().setDefaultSectionSize(87)
        self.tableWidgetWGE.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetWGE.verticalHeader().setDefaultSectionSize(18)
        self.tableWidgetWGE.verticalHeader().setMinimumSectionSize(10)
        self.gridLayout.addWidget(self.tableWidgetWGE, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(211, 400))
        self.groupBox.setMaximumSize(QtCore.QSize(220, 400))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMaximumSize(QtCore.QSize(180, 148))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButtonLoadData = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonLoadData.sizePolicy().hasHeightForWidth())
        self.radioButtonLoadData.setSizePolicy(sizePolicy)
        self.radioButtonLoadData.setChecked(True)
        self.radioButtonLoadData.setObjectName(_fromUtf8("radioButtonLoadData"))
        self.verticalLayout_3.addWidget(self.radioButtonLoadData)
        self.radioButtonSelectAll = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonSelectAll.sizePolicy().hasHeightForWidth())
        self.radioButtonSelectAll.setSizePolicy(sizePolicy)
        self.radioButtonSelectAll.setObjectName(_fromUtf8("radioButtonSelectAll"))
        self.verticalLayout_3.addWidget(self.radioButtonSelectAll)
        self.radioButtonClearAll = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonClearAll.sizePolicy().hasHeightForWidth())
        self.radioButtonClearAll.setSizePolicy(sizePolicy)
        self.radioButtonClearAll.setObjectName(_fromUtf8("radioButtonClearAll"))
        self.verticalLayout_3.addWidget(self.radioButtonClearAll)
        self.radioButtonRemoveSelected = QtGui.QRadioButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonRemoveSelected.sizePolicy().hasHeightForWidth())
        self.radioButtonRemoveSelected.setSizePolicy(sizePolicy)
        self.radioButtonRemoveSelected.setObjectName(_fromUtf8("radioButtonRemoveSelected"))
        self.verticalLayout_3.addWidget(self.radioButtonRemoveSelected)
        self.pushButtonUpdate = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUpdate.sizePolicy().hasHeightForWidth())
        self.pushButtonUpdate.setSizePolicy(sizePolicy)
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.verticalLayout_3.addWidget(self.pushButtonUpdate)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setMaximumSize(QtCore.QSize(180, 16777215))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(180, 193))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.lineEditGroupName = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditGroupName.setObjectName(_fromUtf8("lineEditGroupName"))
        self.verticalLayout_2.addWidget(self.lineEditGroupName)
        self.radioButtonGroupWS = QtGui.QRadioButton(self.groupBox_5)
        self.radioButtonGroupWS.setObjectName(_fromUtf8("radioButtonGroupWS"))
        self.verticalLayout_2.addWidget(self.radioButtonGroupWS)
        self.radioButtonSumWS = QtGui.QRadioButton(self.groupBox_5)
        self.radioButtonSumWS.setObjectName(_fromUtf8("radioButtonSumWS"))
        self.verticalLayout_2.addWidget(self.radioButtonSumWS)
        self.radioButtonMergeWS = QtGui.QRadioButton(self.groupBox_5)
        self.radioButtonMergeWS.setObjectName(_fromUtf8("radioButtonMergeWS"))
        self.verticalLayout_2.addWidget(self.radioButtonMergeWS)
        self.radioButtonExecuteEqn = QtGui.QRadioButton(self.groupBox_5)
        self.radioButtonExecuteEqn.setObjectName(_fromUtf8("radioButtonExecuteEqn"))
        self.verticalLayout_2.addWidget(self.radioButtonExecuteEqn)
        self.pushButtonCreateWorkspace = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonCreateWorkspace.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCreateWorkspace.sizePolicy().hasHeightForWidth())
        self.pushButtonCreateWorkspace.setSizePolicy(sizePolicy)
        self.pushButtonCreateWorkspace.setToolTip(_fromUtf8(""))
        self.pushButtonCreateWorkspace.setObjectName(_fromUtf8("pushButtonCreateWorkspace"))
        self.verticalLayout_2.addWidget(self.pushButtonCreateWorkspace)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 2, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(661, 81))
        self.groupBox_2.setMaximumSize(QtCore.QSize(661, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.lineEditEquation = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditEquation.setObjectName(_fromUtf8("lineEditEquation"))
        self.verticalLayout.addWidget(self.lineEditEquation)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 2, 1)
        self.pushButtonDone = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDone.sizePolicy().hasHeightForWidth())
        self.pushButtonDone.setSizePolicy(sizePolicy)
        self.pushButtonDone.setMinimumSize(QtCore.QSize(141, 23))
        self.pushButtonDone.setObjectName(_fromUtf8("pushButtonDone"))
        self.gridLayout_2.addWidget(self.pushButtonDone, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(66, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        WorkspaceComposer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(WorkspaceComposer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        WorkspaceComposer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(WorkspaceComposer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        WorkspaceComposer.setStatusBar(self.statusbar)

        self.retranslateUi(WorkspaceComposer)
        QtCore.QObject.connect(self.centralwidget, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), self.centralwidget.show)
        QtCore.QObject.connect(self.pushButtonUpdate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonUpdate.show)
        QtCore.QObject.connect(self.pushButtonCreateWorkspace, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.radioButtonLoadData.show)
        QtCore.QObject.connect(self.pushButtonDone, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonDone.show)
        QtCore.QMetaObject.connectSlotsByName(WorkspaceComposer)

    def retranslateUi(self, WorkspaceComposer):
        WorkspaceComposer.setWindowTitle(QtGui.QApplication.translate("WorkspaceComposer", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("WorkspaceComposer", "Workspace List", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("WorkspaceComposer", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("WorkspaceComposer", "Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("WorkspaceComposer", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("WorkspaceComposer", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("WorkspaceComposer", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("WorkspaceComposer", "In Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetWGE.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("WorkspaceComposer", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("WorkspaceComposer", "Select Data", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonLoadData.setText(QtGui.QApplication.translate("WorkspaceComposer", "Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSelectAll.setText(QtGui.QApplication.translate("WorkspaceComposer", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonClearAll.setText(QtGui.QApplication.translate("WorkspaceComposer", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRemoveSelected.setText(QtGui.QApplication.translate("WorkspaceComposer", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUpdate.setText(QtGui.QApplication.translate("WorkspaceComposer", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("WorkspaceComposer", "Select Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("WorkspaceComposer", "Resulting Workspace Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditGroupName.setText(QtGui.QApplication.translate("WorkspaceComposer", "NewWorkspace", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonGroupWS.setText(QtGui.QApplication.translate("WorkspaceComposer", "Group Workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonSumWS.setText(QtGui.QApplication.translate("WorkspaceComposer", "Sum Workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonMergeWS.setText(QtGui.QApplication.translate("WorkspaceComposer", "Merge Workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonExecuteEqn.setText(QtGui.QApplication.translate("WorkspaceComposer", "Execute Equation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCreateWorkspace.setText(QtGui.QApplication.translate("WorkspaceComposer", "Create Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("WorkspaceComposer", "Workspace Algebra Section", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("WorkspaceComposer", "Enter Equation - use workspace names or indicies from the table above, for example:  (ws0-ws1)/ws2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditEquation.setToolTip(QtGui.QApplication.translate("WorkspaceComposer", "Enter an equation using the workspace indicies listed in the Workspace List above.  The shorter Index names are used for convenience.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDone.setText(QtGui.QApplication.translate("WorkspaceComposer", "Done", None, QtGui.QApplication.UnicodeUTF8))

