# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkspaceComposer.ui'
#
# Created: Mon Apr 21 16:58:32 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WorkspaceComposer(object):
    def setupUi(self, WorkspaceComposer):
        WorkspaceComposer.setObjectName(_fromUtf8("WorkspaceComposer"))
        WorkspaceComposer.resize(1069, 384)
        self.centralwidget = QtGui.QWidget(WorkspaceComposer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tableWidgetWGE = QtGui.QTableWidget(self.centralwidget)
        self.tableWidgetWGE.setGeometry(QtCore.QRect(10, 20, 751, 321))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tableWidgetWGE.sizePolicy().hasHeightForWidth())
        self.tableWidgetWGE.setSizePolicy(sizePolicy)
        self.tableWidgetWGE.setRowCount(16)
        self.tableWidgetWGE.setObjectName(_fromUtf8("tableWidgetWGE"))
        self.tableWidgetWGE.setColumnCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(4, item)
        self.tableWidgetWGE.verticalHeader().setDefaultSectionSize(18)
        self.tableWidgetWGE.verticalHeader().setMinimumSectionSize(15)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 20, 281, 321))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditGroupName = QtGui.QLineEdit(self.groupBox)
        self.lineEditGroupName.setGeometry(QtCore.QRect(100, 20, 171, 20))
        self.lineEditGroupName.setObjectName(_fromUtf8("lineEditGroupName"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditGroupComment = QtGui.QLineEdit(self.groupBox)
        self.lineEditGroupComment.setGeometry(QtCore.QRect(100, 50, 171, 20))
        self.lineEditGroupComment.setObjectName(_fromUtf8("lineEditGroupComment"))
        self.radioButtonSelectAll = QtGui.QRadioButton(self.groupBox)
        self.radioButtonSelectAll.setGeometry(QtCore.QRect(40, 100, 82, 17))
        self.radioButtonSelectAll.setObjectName(_fromUtf8("radioButtonSelectAll"))
        self.radioButtonClearAll = QtGui.QRadioButton(self.groupBox)
        self.radioButtonClearAll.setGeometry(QtCore.QRect(40, 120, 82, 17))
        self.radioButtonClearAll.setObjectName(_fromUtf8("radioButtonClearAll"))
        self.radioButtonRemoveSelected = QtGui.QRadioButton(self.groupBox)
        self.radioButtonRemoveSelected.setGeometry(QtCore.QRect(40, 140, 111, 17))
        self.radioButtonRemoveSelected.setObjectName(_fromUtf8("radioButtonRemoveSelected"))
        self.radioButtonChooseWorkspace = QtGui.QRadioButton(self.groupBox)
        self.radioButtonChooseWorkspace.setGeometry(QtCore.QRect(40, 80, 141, 17))
        self.radioButtonChooseWorkspace.setChecked(True)
        self.radioButtonChooseWorkspace.setObjectName(_fromUtf8("radioButtonChooseWorkspace"))
        self.pushButtonUpdate = QtGui.QPushButton(self.groupBox)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(180, 110, 75, 23))
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.labelStatusMsg = QtGui.QLabel(self.groupBox)
        self.labelStatusMsg.setGeometry(QtCore.QRect(10, 250, 261, 16))
        self.labelStatusMsg.setObjectName(_fromUtf8("labelStatusMsg"))
        self.checkBoxEnforceCompatibility = QtGui.QCheckBox(self.groupBox)
        self.checkBoxEnforceCompatibility.setEnabled(False)
        self.checkBoxEnforceCompatibility.setGeometry(QtCore.QRect(40, 200, 201, 17))
        self.checkBoxEnforceCompatibility.setChecked(True)
        self.checkBoxEnforceCompatibility.setObjectName(_fromUtf8("checkBoxEnforceCompatibility"))
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(120, 280, 156, 31))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.labelNumWorkspaces = QtGui.QLabel(self.groupBox)
        self.labelNumWorkspaces.setGeometry(QtCore.QRect(10, 230, 261, 16))
        self.labelNumWorkspaces.setObjectName(_fromUtf8("labelNumWorkspaces"))
        self.checkBoxSumWorkspaces = QtGui.QCheckBox(self.groupBox)
        self.checkBoxSumWorkspaces.setGeometry(QtCore.QRect(40, 180, 131, 17))
        self.checkBoxSumWorkspaces.setObjectName(_fromUtf8("checkBoxSumWorkspaces"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 160, 261, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        WorkspaceComposer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(WorkspaceComposer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        WorkspaceComposer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(WorkspaceComposer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        WorkspaceComposer.setStatusBar(self.statusbar)

        self.retranslateUi(WorkspaceComposer)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), self.buttonBox.show)
        QtCore.QObject.connect(self.centralwidget, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), self.centralwidget.show)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.buttonBox.show)
        QtCore.QObject.connect(self.pushButtonUpdate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonUpdate.show)
        QtCore.QMetaObject.connectSlotsByName(WorkspaceComposer)

    def retranslateUi(self, WorkspaceComposer):
        WorkspaceComposer.setWindowTitle(_translate("WorkspaceComposer", "MainWindow", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(0)
        item.setText(_translate("WorkspaceComposer", "Workspace", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(1)
        item.setText(_translate("WorkspaceComposer", "Location", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(2)
        item.setText(_translate("WorkspaceComposer", "Date", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(3)
        item.setText(_translate("WorkspaceComposer", "Size", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(4)
        item.setText(_translate("WorkspaceComposer", "Select", None))
        self.lineEditGroupName.setText(_translate("WorkspaceComposer", "NewWorkspaceGroup", None))
        self.label.setText(_translate("WorkspaceComposer", "Group Name", None))
        self.label_2.setText(_translate("WorkspaceComposer", "Group Comment", None))
        self.lineEditGroupComment.setText(_translate("WorkspaceComposer", "NewGroupComment", None))
        self.radioButtonSelectAll.setText(_translate("WorkspaceComposer", "Select All", None))
        self.radioButtonClearAll.setText(_translate("WorkspaceComposer", "Clear All", None))
        self.radioButtonRemoveSelected.setText(_translate("WorkspaceComposer", "Remove Selected", None))
        self.radioButtonChooseWorkspace.setText(_translate("WorkspaceComposer", "Choose Workspace(s)", None))
        self.pushButtonUpdate.setText(_translate("WorkspaceComposer", "Update", None))
        self.labelStatusMsg.setText(_translate("WorkspaceComposer", "Status Message:", None))
        self.checkBoxEnforceCompatibility.setText(_translate("WorkspaceComposer", "Enforce Workspace Compatibility", None))
        self.labelNumWorkspaces.setText(_translate("WorkspaceComposer", "Number of Workspaces: ", None))
        self.checkBoxSumWorkspaces.setText(_translate("WorkspaceComposer", "Sum Workspaces", None))

