# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkspaceComposer.ui'
#
# Created: Thu May 08 11:57:18 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WorkspaceComposer(object):
    def setupUi(self, WorkspaceComposer):
        WorkspaceComposer.setObjectName(_fromUtf8("WorkspaceComposer"))
        WorkspaceComposer.resize(1074, 525)
        self.centralwidget = QtGui.QWidget(WorkspaceComposer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 30, 281, 321))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEditGroupName = QtGui.QLineEdit(self.groupBox)
        self.lineEditGroupName.setGeometry(QtCore.QRect(100, 20, 171, 20))
        self.lineEditGroupName.setObjectName(_fromUtf8("lineEditGroupName"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEditGroupComment = QtGui.QLineEdit(self.groupBox)
        self.lineEditGroupComment.setGeometry(QtCore.QRect(100, 50, 171, 20))
        self.lineEditGroupComment.setObjectName(_fromUtf8("lineEditGroupComment"))
        self.radioButtonSelectAll = QtGui.QRadioButton(self.groupBox)
        self.radioButtonSelectAll.setGeometry(QtCore.QRect(40, 100, 82, 17))
        self.radioButtonSelectAll.setObjectName(_fromUtf8("radioButtonSelectAll"))
        self.radioButtonClearAll = QtGui.QRadioButton(self.groupBox)
        self.radioButtonClearAll.setGeometry(QtCore.QRect(40, 120, 82, 17))
        self.radioButtonClearAll.setObjectName(_fromUtf8("radioButtonClearAll"))
        self.radioButtonRemoveSelected = QtGui.QRadioButton(self.groupBox)
        self.radioButtonRemoveSelected.setGeometry(QtCore.QRect(40, 140, 111, 17))
        self.radioButtonRemoveSelected.setObjectName(_fromUtf8("radioButtonRemoveSelected"))
        self.radioButtonChooseWorkspace = QtGui.QRadioButton(self.groupBox)
        self.radioButtonChooseWorkspace.setGeometry(QtCore.QRect(40, 80, 211, 17))
        self.radioButtonChooseWorkspace.setChecked(True)
        self.radioButtonChooseWorkspace.setObjectName(_fromUtf8("radioButtonChooseWorkspace"))
        self.pushButtonUpdate = QtGui.QPushButton(self.groupBox)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(180, 110, 75, 23))
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.checkBoxEnforceCompatibility = QtGui.QCheckBox(self.groupBox)
        self.checkBoxEnforceCompatibility.setEnabled(False)
        self.checkBoxEnforceCompatibility.setGeometry(QtCore.QRect(40, 200, 231, 17))
        self.checkBoxEnforceCompatibility.setChecked(True)
        self.checkBoxEnforceCompatibility.setObjectName(_fromUtf8("checkBoxEnforceCompatibility"))
        self.checkBoxSumWorkspaces = QtGui.QCheckBox(self.groupBox)
        self.checkBoxSumWorkspaces.setGeometry(QtCore.QRect(40, 180, 181, 17))
        self.checkBoxSumWorkspaces.setObjectName(_fromUtf8("checkBoxSumWorkspaces"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 160, 261, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 370, 751, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEditResultingWorkspace = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditResultingWorkspace.setGeometry(QtCore.QRect(30, 50, 191, 20))
        self.lineEditResultingWorkspace.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.lineEditResultingWorkspace.setObjectName(_fromUtf8("lineEditResultingWorkspace"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(240, 50, 46, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEditEquation = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditEquation.setGeometry(QtCore.QRect(270, 50, 471, 20))
        self.lineEditEquation.setObjectName(_fromUtf8("lineEditEquation"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(270, 30, 471, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(770, 370, 281, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox_3)
        self.buttonBox.setGeometry(QtCore.QRect(120, 70, 156, 31))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.labelStatusMsg = QtGui.QLabel(self.groupBox_3)
        self.labelStatusMsg.setGeometry(QtCore.QRect(10, 40, 261, 16))
        self.labelStatusMsg.setObjectName(_fromUtf8("labelStatusMsg"))
        self.labelNumWorkspaces = QtGui.QLabel(self.groupBox_3)
        self.labelNumWorkspaces.setGeometry(QtCore.QRect(10, 20, 261, 16))
        self.labelNumWorkspaces.setObjectName(_fromUtf8("labelNumWorkspaces"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 751, 341))
        self.groupBox_4.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);\n"
""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tableWidgetWGE = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidgetWGE.setGeometry(QtCore.QRect(10, 20, 730, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tableWidgetWGE.sizePolicy().hasHeightForWidth())
        self.tableWidgetWGE.setSizePolicy(sizePolicy)
        self.tableWidgetWGE.setMaximumSize(QtCore.QSize(730, 300))
        self.tableWidgetWGE.setSizeIncrement(QtCore.QSize(5, 5))
        self.tableWidgetWGE.setLineWidth(3)
        self.tableWidgetWGE.setRowCount(15)
        self.tableWidgetWGE.setObjectName(_fromUtf8("tableWidgetWGE"))
        self.tableWidgetWGE.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetWGE.setHorizontalHeaderItem(5, item)
        self.tableWidgetWGE.verticalHeader().setDefaultSectionSize(18)
        self.tableWidgetWGE.verticalHeader().setMinimumSectionSize(15)
        WorkspaceComposer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(WorkspaceComposer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        WorkspaceComposer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(WorkspaceComposer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        WorkspaceComposer.setStatusBar(self.statusbar)

        self.retranslateUi(WorkspaceComposer)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), self.buttonBox.show)
        QtCore.QObject.connect(self.centralwidget, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), self.centralwidget.show)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), self.buttonBox.show)
        QtCore.QObject.connect(self.pushButtonUpdate, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonUpdate.show)
        QtCore.QMetaObject.connectSlotsByName(WorkspaceComposer)

    def retranslateUi(self, WorkspaceComposer):
        WorkspaceComposer.setWindowTitle(_translate("WorkspaceComposer", "MainWindow", None))
        self.lineEditGroupName.setText(_translate("WorkspaceComposer", "NewWorkspaceGroup", None))
        self.label.setText(_translate("WorkspaceComposer", "Group Name", None))
        self.label_2.setText(_translate("WorkspaceComposer", "Group Comment", None))
        self.lineEditGroupComment.setText(_translate("WorkspaceComposer", "NewGroupComment", None))
        self.radioButtonSelectAll.setText(_translate("WorkspaceComposer", "Select All", None))
        self.radioButtonClearAll.setText(_translate("WorkspaceComposer", "Clear All", None))
        self.radioButtonRemoveSelected.setText(_translate("WorkspaceComposer", "Remove Selected", None))
        self.radioButtonChooseWorkspace.setText(_translate("WorkspaceComposer", "Choose Workspace(s)", None))
        self.pushButtonUpdate.setText(_translate("WorkspaceComposer", "Update", None))
        self.checkBoxEnforceCompatibility.setText(_translate("WorkspaceComposer", "Enforce Workspace Compatibility", None))
        self.checkBoxSumWorkspaces.setText(_translate("WorkspaceComposer", "Sum Workspaces", None))
        self.groupBox_2.setTitle(_translate("WorkspaceComposer", "Workspace Algebra Section", None))
        self.lineEditResultingWorkspace.setToolTip(_translate("WorkspaceComposer", "Enter the name of the workspace to contain the results of the equation", None))
        self.lineEditResultingWorkspace.setText(_translate("WorkspaceComposer", "AlgWorkspace", None))
        self.label_3.setText(_translate("WorkspaceComposer", "=", None))
        self.lineEditEquation.setToolTip(_translate("WorkspaceComposer", "Enter an equation using the workspace indicies listed in the Workspace List above.  The shorter Index names are used for convenience.", None))
        self.label_4.setText(_translate("WorkspaceComposer", "Resulting Workspace Name", None))
        self.label_5.setText(_translate("WorkspaceComposer", "Enter Equation - use workspace indicies, for example:  (ws1-ws2)/ws3", None))
        self.groupBox_3.setTitle(_translate("WorkspaceComposer", "Perform Task", None))
        self.labelStatusMsg.setText(_translate("WorkspaceComposer", "Status Message:", None))
        self.labelNumWorkspaces.setText(_translate("WorkspaceComposer", "Number of Workspaces: ", None))
        self.groupBox_4.setTitle(_translate("WorkspaceComposer", "Workspace List", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(0)
        item.setText(_translate("WorkspaceComposer", "Index", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(1)
        item.setText(_translate("WorkspaceComposer", "Workspace", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(2)
        item.setText(_translate("WorkspaceComposer", "Location", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(3)
        item.setText(_translate("WorkspaceComposer", "Date", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(4)
        item.setText(_translate("WorkspaceComposer", "Size", None))
        item = self.tableWidgetWGE.horizontalHeaderItem(5)
        item.setText(_translate("WorkspaceComposer", "Select", None))

